### ISSUE TITLE
Can't add 2 urls using decorators for function in new version (19.12)

### ISSUE THREAD

**Issue by pi11** [sanic-org/sanic#1773]
So in previous version I was using something like this:
```

@app.get('/embed/<video_id:int>', strict_slashes=False)
@app.get('/<video_id:int>', strict_slashes=False)
async def embed_video(request, video_id): 
    ....
```
Everything works just fine, in new version I got error:

```

Traceback (most recent call last):
  File "main.py", line 84, in <module>
    @app.get('/<video_id:int>', strict_slashes=False)
  File "/home/serge/work/ve/lib/python3.7/site-packages/sanic/app.py", line 197, in response
    args = list(signature(handler).parameters.keys())
  File "/usr/lib/python3.7/inspect.py", line 3083, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/usr/lib/python3.7/inspect.py", line 2833, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/usr/lib/python3.7/inspect.py", line 2208, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: ([Route(handler=<function embed_video at 0x7f5463598400>, methods=frozenset({'GET'}), pattern=re.compile('^/(-?\\d+)$'), parameters=[Parameter(name='video_id', cast=<class 'int'>)], name='embed_video', uri='/<video_id:int>'), Route(handler=<function embed_video at 0x7f5463598400>, methods=frozenset({'GET'}), pattern=re.compile('^/(-?\\d+)/$'), parameters=[Parameter(name='video_id', cast=<class 'int'>)], name='embed_video', uri='/<video_id:int>/')], <function embed_video at 0x7f5463598400>) is not a callable object
```

I also tried decorator + adding add_route, here example code:

```
from sanic import Sanic
from sanic.response import json

app = Sanic()

@app.route("/")
async def test(request):
    return json({"hello": "world"})

if __name__ == "__main__":
    app.add_route(test, '/test')
    app.run(host="0.0.0.0", port=8000)
  
```
And got same error. 

So the only way to add 2 urls for 1 function is using add_route - which work perfect.
Not sure if this is expected behavior from now on or a bug?

**Comment by Tronic** [comment]
This was a bug, already fixed in git master but I am not sure if a fixed version was already released.

**Comment by sjsadowski** [comment]
This is fixed in master, I need to figure out what PR it is to get it in to 19.12.3 and do a release.

**Comment by harshanarayana** [comment]
xref: b565072

@sjsadowski  I believe the above commit fixed this problem in master
