### ISSUE TITLE
h2 4.0.0 breaks httpx 0.11 breaks sanic 20.6.3 with ImportError

### ISSUE THREAD

**Issue by ar4hc** [sanic-org/sanic#1932]
### Describe the bug

Not a real bug just an incompatible update in an used dependenciy, i assume "h2" 4.0.0, used by httpx.

when using h2 4.0 there is always an exception ImportError thrown , h2 3.2 works.

### To reproduce

install h2 version 4.0.0 (released 19.9.), start using httpx, in may case from sanic 20.6.3, the script will crash with below exception

### Expected behavior

No exception, imports the correct modules, i assume,

### Actual behavior

Throws an exception:
```
ImportError: cannot import name 'InvalidDataError' from 'hyperframe.exceptions'
```

### Debugging material

Here is my stacktrace:
```
Traceback (most recent call last):
  File "./main.py", line 22, in <module>
    from sanic import Sanic, response
  File "/usr/local/miniconda3/envs/web/lib/python3.8/site-packages/sanic/__init__.py", line 2, in <module>
    from sanic.app import Sanic
  File "/usr/local/miniconda3/envs/web/lib/python3.8/site-packages/sanic/app.py", line 35, in <module>
    from sanic.testing import SanicASGITestClient, SanicTestClient
  File "/usr/local/miniconda3/envs/web/lib/python3.8/site-packages/sanic/testing.py", line 4, in <module>
    import httpx
  File "/usr/local/miniconda3/envs/web/lib/python3.8/site-packages/httpx/__init__.py", line 2, in <module>
    from .api import delete, get, head, options, patch, post, put, request, stream
  File "/usr/local/miniconda3/envs/web/lib/python3.8/site-packages/httpx/api.py", line 4, in <module>
    from .client import Client, StreamContextManager
  File "/usr/local/miniconda3/envs/web/lib/python3.8/site-packages/httpx/client.py", line 26, in <module>
    from .dispatch.connection_pool import ConnectionPool
  File "/usr/local/miniconda3/envs/web/lib/python3.8/site-packages/httpx/dispatch/connection_pool.py", line 16, in <module>
    from .connection import HTTPConnection
  File "/usr/local/miniconda3/envs/web/lib/python3.8/site-packages/httpx/dispatch/connection.py", line 11, in <module>
    from .http2 import HTTP2Connection
  File "/usr/local/miniconda3/envs/web/lib/python3.8/site-packages/httpx/dispatch/http2.py", line 3, in <module>
    import h2.connection
  File "/usr/local/miniconda3/envs/web/lib/python3.8/site-packages/h2/connection.py", line 33, in <module>
    from .frame_buffer import FrameBuffer
  File "/usr/local/miniconda3/envs/web/lib/python3.8/site-packages/h2/frame_buffer.py", line 9, in <module>
    from hyperframe.exceptions import InvalidFrameError, InvalidDataError
ImportError: cannot import name 'InvalidDataError' from 'hyperframe.exceptions' (/usr/local/miniconda3/envs/web/lib/python3.8/site-packages/hyperframe/exceptions.py)
```

### Environment

- OS: macos
- Python version: 3.8.5 
- HTTPX version:  0.11.1  
- Async environment:  sanic 20.6.3  

### Additional context

a small api using sanic which uses httpx which uses h2 which was recently updated and broke some stuff.

**Comment by ahopkins** [comment]
Thanks. Httpx will soon be removed from core dependency. New Sanic release coming next week will deal with this.

**Comment by ahopkins** [comment]
Just an upgrade for now. We are not yet removing the dependency.

**Comment by ahopkins** [comment]
Dependency upon httpx to be removed in 21.3
