### ISSUE TITLE
Recursion occurs when registering a Blueprint group

### ISSUE THREAD

**Issue by SaidBySolo** [sanic-org/sanic#2071]
**Describe the bug**
```
Traceback (most recent call last):
  File "F:\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\saidb\Documents\GitHub\Heliotrope\heliotrope\__main__.py", line 3, in <module>
    from heliotrope.server import heliotrope
  File "C:\Users\saidb\Documents\GitHub\Heliotrope\heliotrope\server.py", line 40, in <module>
    heliotrope = Heliotrope("heliotrope")
  File "F:\Python\Python39\lib\site-packages\sanic\base.py", line 24, in __init__
    base.__init__(self, *args, **kwargs)
  File "F:\Python\Python39\lib\site-packages\sanic\base.py", line 24, in __init__
    base.__init__(self, *args, **kwargs)
  File "F:\Python\Python39\lib\site-packages\sanic\base.py", line 24, in __init__
    base.__init__(self, *args, **kwargs)
  [Previous line repeated 984 more times]
  File "F:\Python\Python39\lib\site-packages\sanic\base.py", line 20, in __init__
    b for base in type(self).__bases__ for b in base.__bases__
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Code snippet**
```py
# in etc __init__
from sanic.blueprints import Blueprint

from app.api.etc.endpoint_one import one
from app.api.etc.endpoint_two import two
from app.api.etc.endpoint_three import three
from app.api.etc.endpoint_four import four

etc_endpoint = Blueprint.group(
    one,
    two,
    three,
    four,
    url_prefix="/endpoint",
)
```

```py
# in api __init__
from sanic.blueprints import Blueprint

from app.api.etc import etc_endpoint
from app.api.fun import fun

app_endpoint = Blueprint.group(etc_endpoint, fun, url_prefix="api")
```

```py
# in app.py
class Custom(Sanic):
    def __init__(
        self,
        name=None,
        router=None,
        error_handler=None,
        load_env=True,
        request_class=None,
        strict_slashes=False,
        log_config=None,
        configure_logging=True,
        register=None,
    ):
        self.requester: Optional[Requester] = None
        super().__init__(
            name=name,
            router=router,
            error_handler=error_handler,
            load_env=load_env,
            request_class=request_class,
            strict_slashes=strict_slashes,
            log_config=log_config,
            configure_logging=configure_logging,
            register=register,
        )

custom = Custom("custom")

custom.blueprint(app_endpoint)
```

**Expected behavior**

It must be registered normally

**Environment (please complete the following information):**
 - OS: Windows 10
 - Version Sanic 21.3.0a1

Additional context

In Sanic 20.12.2 it works as expected.

**Comment by artcg** [comment]
Not anything to do with blueprints, minimal code to reproduce

```python
from sanic import Sanic


class Custom(Sanic):
    def __init__(self, name):
        self.requester = None
        super().__init__(name)


custom = Custom("custom")
```

Why are you trying to set that value self.requester? It doesn't seem to be part of the Sanic class at all

**Comment by artcg** [comment]
if that 'requester' attribute is part of your code and you need it available for something, best to set app.ctx.requester after initialisation, or via a listener
