### ISSUE TITLE
[documentation] sanic.response.file - wrong example

### ISSUE THREAD

**Issue by prof7bit** [sanic-org/sanic#2093]
the example given in the documentation: https://sanicframework.org/en/guide/basics/response.html#file to return a file suggests to write:
```
from sanic.response import file

@app.route("/")
async def handler(request):
    return file("/path/to/whatever.png")
```
But this will result in an error:
```
/home/bernd/proj/sanic-server/venv/bin/python /home/bernd/proj/sanic-server/main.py
[2021-03-28 17:45:16 +0200] [146260] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2021-03-28 17:45:16 +0200] [146260] [INFO] Starting worker [146260]
[2021-03-28 17:45:31 +0200] [146260] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:8000/'
Traceback (most recent call last):
  File "/home/bernd/proj/sanic-server/venv/lib/python3.8/site-packages/sanic/app.py", line 737, in handle_request
    handler.is_websocket  # type: ignore
AttributeError: 'function' object has no attribute 'is_websocket'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bernd/proj/sanic-server/venv/lib/python3.8/site-packages/sanic/app.py", line 739, in handle_request
    raise ServerError(
sanic.exceptions.ServerError: Invalid response type <coroutine object file at 0x7f4690a04640> (need HTTPResponse)
[2021-03-28 17:45:31 +0200] - (sanic.access)[INFO][127.0.0.1:59714]: GET http://127.0.0.1:8000/  500 -1
/home/bernd/proj/sanic-server/venv/lib/python3.8/site-packages/sanic/http.py:125: RuntimeWarning: coroutine 'file' was never awaited
  await self.protocol.request_handler(self.request)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
and in the browser it will show:
```
⚠️ 500 — Internal Server Error

Invalid response type <coroutine object file at 0x7f4690a04640> (need HTTPResponse) 
```

If I put ```await``` in front of ```file``` it will work. So I guess the documentation is wrong.

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.10
 - Sanic 21.3.2

**Comment by ahopkins** [comment]
Thanks. Can you submit a PR? You can click the "Edit this page on GitHub" link at the bottom of the page.

**Comment by ahopkins** [comment]
Closing in favor of the PR. (not sure if GH allows cross repo linked PRs)
