### ISSUE TITLE
Reuse of blueprint groups causes duplicate route errors

### ISSUE THREAD

**Issue by jdraymon** [sanic-org/sanic#2113]
**Describe the bug**

When adding a blueprint to multiple groups, the router seems to club `url_prefix`es together in an unexpected way, resulting in duplicate route errors.

```
Traceback (most recent call last):
  File "/home/jraymond/Development/sanic-org/bugreport/bugreport/app.py", line 26, in <module>
    app.blueprint(new)
  File "/home/jraymond/Development/sanic-org/sanic/sanic/app.py", line 407, in blueprint
    self.blueprint(item, **options)
  File "/home/jraymond/Development/sanic-org/sanic/sanic/app.py", line 423, in blueprint
    blueprint.register(self, options)
  File "/home/jraymond/Development/sanic-org/sanic/sanic/blueprints.py", line 227, in register
    route = app._apply_route(apply_route)
  File "/home/jraymond/Development/sanic-org/sanic/sanic/app.py", line 337, in _apply_route
    routes = self.router.add(**params)
  File "/home/jraymond/Development/sanic-org/sanic/sanic/router.py", line 128, in add
    route = super().add(**params)  # type: ignore
  File "/home/jraymond/.local/lib/python3.9/site-packages/sanic_routing/router.py", line 170, in add
    route.add_handler(path, handler, method, requirements, overwrite)
  File "/home/jraymond/.local/lib/python3.9/site-packages/sanic_routing/route.py", line 114, in add_handler
    raise RouteExists(
sanic_routing.exceptions.RouteExists: Route already registered: api/new/v1/api/v1/hello [GET]
```

**Code snippet**
Minimal reproduction:
```python
from sanic import Blueprint, Sanic
from sanic.response import text


bp1 = Blueprint("bp1", url_prefix="/hello")


@bp1.get("/")
async def hello(_):
    return text("hello")


bp2 = Blueprint("bp2", url_prefix="/goodbye")


@bp2.get("/")
async def goodbye(_):
    return text("goodbye")


legacy = Blueprint.group([bp1, bp2], url_prefix="/api/v1")
new = Blueprint.group([bp1, bp2], url_prefix="/api/new/v1")

app = Sanic("bugreport")
app.blueprint(legacy)
app.blueprint(new)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=1234, debug=True)
```

**Expected behavior**
Blueprint groups should be independent references to handlers:
```
GET: /api/thing/v1/hello => "hello"
GET: /api/v1/hello => "hello"
```

**Environment (please complete the following information):**
 - OS: Linux (Arch)
 - Python: 3.9
 - Version 21.3.2

**Comment by jdraymon** [comment]
Problem appears [to be here](https://github.com/sanic-org/sanic/blob/e21521f45c0b58bac619a9111fd47426e208bf08/sanic/blueprint_group.py#L176). Not sure if there's an obvious fix, but the API for blueprint groups doesn't indicate that the op is destructive. Can try to come up with sth if nobody beats me to the punch

**Comment by ashleysommer** [comment]
Thanks @jdraymon for the great bug report.
The 21.3 release included a new router and backend server, along with those changes came some some necessary modifications to the way url_prefixes work. I guess there is simply no test in the Sanic test suite that tests adding a blueprint to multiple bp groups.

**Comment by jdraymon** [comment]
@ashleysommer Running with version 20.12.3 produces a similar stack trace:
```
Traceback (most recent call last):
  File "/home/jraymond/Development/sanic-org/bugreport/bugreport/app.py", line 26, in <module>
    app.blueprint(new)
  File "/home/jraymond/.cache/pypoetry/virtualenvs/bugreport-qBp1ZuVR-py3.9/lib/python3.9/site-packages/sanic/app.py", line 707, in blueprint
    self.blueprint(item, **options)
  File "/home/jraymond/.cache/pypoetry/virtualenvs/bugreport-qBp1ZuVR-py3.9/lib/python3.9/site-packages/sanic/app.py", line 717, in blueprint
    blueprint.register(self, options)
  File "/home/jraymond/.cache/pypoetry/virtualenvs/bugreport-qBp1ZuVR-py3.9/lib/python3.9/site-packages/sanic/blueprints.py", line 119, in register
    _routes, _ = app.route(
  File "/home/jraymond/.cache/pypoetry/virtualenvs/bugreport-qBp1ZuVR-py3.9/lib/python3.9/site-packages/sanic/app.py", line 211, in response
    self.router.add(
  File "/home/jraymond/.cache/pypoetry/virtualenvs/bugreport-qBp1ZuVR-py3.9/lib/python3.9/site-packages/sanic/router.py", line 158, in add
    routes.append(self._add(uri, methods, handler, host, name))
  File "/home/jraymond/.cache/pypoetry/virtualenvs/bugreport-qBp1ZuVR-py3.9/lib/python3.9/site-packages/sanic/router.py", line 317, in _add
    route = merge_route(route, methods, handler)
  File "/home/jraymond/.cache/pypoetry/virtualenvs/bugreport-qBp1ZuVR-py3.9/lib/python3.9/site-packages/sanic/router.py", line 267, in merge_route
    raise RouteExists(
sanic.router.RouteExists: Route already registered: /api/new/v1/api/v1/hello/ [GET]
```

**Comment by jdraymon** [comment]
Walked the tree back a goodly long ways and it seems this has always been the behavior, looks like I'm just the first one to try :slightly_smiling_face:

**Comment by ahopkins** [comment]
@jdraymon This is a good report, and I can confirm that this is a problem with the way in which we are applying the URLs. TBH, to solve this properly will require a bit of reworking of the groups. I do agree with @sjsadowski applying the `LTS` label here that we should fix this and then apply it backwards.

I propose that the `BlueprintGroup.append` solution instead of making the change to the blueprint, registers it either on the group instance with a reference (less appealing), or on some property on the blueprint (`blueprint.alternatives`). Then, when the blueprint is added to the router, we simply register the handlers once for each alternative definition that was supplied.

The other problem that the current methodology has (not reported in this issue) is that having blueprints with differing `version` or `strict_slashes` would result in weird and unexpected behaviors as they would override one another.

**Comment by ahopkins** [comment]
Here is the original snippet, albeit slightly modified to add in another layer of grouping and to test version args.

```python
from sanic import Blueprint, Sanic
from sanic.response import text

bp1 = Blueprint("bp1", url_prefix="/hello")


@bp1.get("/")
async def hello(_):
    return text("hello")


bp2 = Blueprint("bp2", url_prefix="/goodbye")


@bp2.get("/")
async def goodbye(_):
    return text("goodbye")


legacy = Blueprint.group([bp1, bp2], url_prefix="/api", version=1)
new = Blueprint.group([bp1, bp2], url_prefix="/new", version=1)
v2 = Blueprint.group(legacy, new, url_prefix="/alt", version=2)

app = Sanic("bugreport")
app.blueprint(legacy)
app.blueprint(new)
app.blueprint(v2)


@app.before_server_start
def display(app, _):
    for route in app.router.routes:
        print(route.path)
```

When we start up, the routes we get are:

```
v1/api/hello
v1/api/goodbye
v1/new/hello
v1/new/goodbye
v1/alt/api/hello
v1/alt/api/goodbye
v1/alt/new/hello
v1/alt/new/goodbye
```

---

Thinking back on this more, I am not sure that I actually agree that this is a bug that we need to backport to 20.12. Really, this is a new feature. The old documentation did not claim that blueprints were infinitely composable. So, while I think this is a novel use, and a really great addition that can make for some nice composable APIs, I am not convinced we need another PR to 20.12.

**Comment by jdraymon** [comment]
@ahopkins thanks for the note - I had been avoiding the version argument for exactly that reason 😄
