### ISSUE TITLE
CancelledError on exit with open websocket connections

### ISSUE THREAD

**Issue by DirtyHairy** [sanic-org/sanic#2185]
**Describe the bug**
I am getting an uncaught `CancelledError` on exit if there is an open websocket connection. Log/Backtrace:

```
[2021-07-08 00:26:33 +0200] [53131] [ERROR] Exception occurred while handling uri: 'wss://192.168.178.20:8667/'
Traceback (most recent call last):
  File "/Users/pestix/.virtualenvs/server-25sdMkop/lib/python3.9/site-packages/sanic/http.py", line 129, in http1
    await self.protocol.request_handler(self.request)
  File "/Users/pestix/.virtualenvs/server-25sdMkop/lib/python3.9/site-packages/sanic/app.py", line 770, in handle_request
    response = await response
  File "/Users/pestix/.virtualenvs/server-25sdMkop/lib/python3.9/site-packages/sanic/app.py", line 826, in _websocket_handler
    await ws.close()
  File "/Users/pestix/.virtualenvs/server-25sdMkop/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 629, in close
    await asyncio.shield(self.close_connection_task)
asyncio.exceptions.CancelledError
```

**Expected behavior**
Graceful exit 😏 

**Environment (please complete the following information):**
 - OS: MacOS
 - Python: 3.9.5
 - Sanic 21.6.0

**Additional context**

**Comment by DirtyHairy** [comment]
I've opened a PR: #2187

**Comment by ahopkins** [comment]
I am curious to know if this is still the case with 21.9
