### ISSUE TITLE
All API's are failing after upgrade to 21.9.3.

### ISSUE THREAD

**Issue by ama-admin** [sanic-org/sanic#2326]
**Describe the bug**
A clear and concise description of what the bug is, make sure to paste any exceptions and tracebacks.

This error started coming up when I upgraded version from 21.3.4 to 21.9.3, When the app starts this is the error that shows up:

```
[2021-12-02 18:33:59 +0530] [6392] [WARNING] You are using a deprecated error handler. The lookup method should accept two positional parameters: (exception, route_name: Optional[str]). Until you upgrade your ErrorHandler.lookup, Blueprint specific exceptions will not work properly. Beginning in v22.3, the legacy style lookup method will not work at all.
```
When I  try to access any API, this is the error popping up on every API.
```

[2021-12-02 18:34:09 +0530] [6390] [ERROR] SPTK caught an error that should have been caught by Sanic response handler.
[2021-12-02 18:34:09 +0530] [6390] [ERROR] Could not find signal http.lifecycle.handle
[2021-12-02 18:34:09 +0530] [6390] [ERROR] Exception occurred while handling uri: 'http://localhost:8080/v1/api/users/ens_name_autocomplete'
Traceback (most recent call last):
  File "/Users/sauravverma/Programs/ama.fans/py-server-backend/lib/python3.8/site-packages/sanic/signals.py", line 73, in get
    group, param_basket = self.find_route(
  File "", line 38, in find_route
sanic_routing.exceptions.NotFound: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sauravverma/Programs/ama.fans/py-server-backend/lib/python3.8/site-packages/sanic/http.py", line 146, in http1
    await self.protocol.request_handler(self.request)
  File "/Users/sauravverma/Programs/ama.fans/py-server-backend/lib/python3.8/site-packages/sanic_plugin_toolkit/realm.py", line 550, in _handle_request_21_03
    _ = await real_handle(request)
  File "/Users/sauravverma/Programs/ama.fans/py-server-backend/lib/python3.8/site-packages/sanic/app.py", line 769, in handle_request
    await self.dispatch(
  File "/Users/sauravverma/Programs/ama.fans/py-server-backend/lib/python3.8/site-packages/sanic/signals.py", line 163, in dispatch
    return await dispatch
  File "/Users/sauravverma/Programs/ama.fans/py-server-backend/lib/python3.8/site-packages/sanic/signals.py", line 114, in _dispatch
    raise e
  File "/Users/sauravverma/Programs/ama.fans/py-server-backend/lib/python3.8/site-packages/sanic/signals.py", line 111, in _dispatch
    group, handlers, params = self.get(event, condition=condition)
  File "/Users/sauravverma/Programs/ama.fans/py-server-backend/lib/python3.8/site-packages/sanic/signals.py", line 86, in get
    raise NotFound(message % tuple(terms))
sanic_routing.exceptions.NotFound: Could not find signal http.lifecycle.handle
```

**Code snippet**
Relevant source code, make sure to remove what is not necessary.
Sharing a part of the code 
```
users/users.py
USERS_BP = Blueprint("users", url_prefix='/users', version=1)

@USERS_BP.post('signup')
async def signup(request):
   return response.json({})

app.py

    APP_BP = Blueprint.group(USERS_BP, SOME_OTHER_BP, url_prefix='/api')
    app.blueprint(APP_BP)

    

    app.run(host="0.0.0.0", port=8080, workers=workers, auto_reload=True, access_log=False,  reload_dir="./config")
```

**Expected behavior**
All the apis were working fine before upgrade.

**Environment (please complete the following information):**
 - OS: [e.g. iOS] Mac osx
 - Version [e.g. 0.8.3] Catalina

**Additional context**

**Comment by ahopkins** [comment]
This issue has been mentioned on **Sanic Community Discussion**. There might be relevant details there:

https://community.sanicframework.org/t/error-after-upgradation-to-new-sanic-version/932/3

**Comment by ahopkins** [comment]
Closing in favor of support in forums
