### ISSUE TITLE
Request middlware runs twice when exception is thrown

### ISSUE THREAD

**Issue by ashleysommer** [sanic-org/sanic#2351]
I can't tell if this is intentional or not. I think I've brought it up before, but its affecting me again when maintaining some of my plugins.

Minimal reproduction:
```python3
from sanic import Sanic
from sanic.exceptions import SanicException
from sanic.response import html

app = Sanic(__name__)

@app.middleware("request")
def my_middleware1(request):
    print("Middleware 1 ran", flush=True)

@app.middleware("request")
def my_middleware2(request):
    print("Middleware 2 ran", flush=True)
    raise SanicException()

@app.get("/")
def index(request):
    return html("<p>hello world</p>")

if __name__ == "__main__":
    app.run(debug=True, auto_reload=False, access_log=False)
```

Output:
```bash
[2022-01-04 13:32:31 +1000] [45332] [INFO] Starting worker [45332]
Middleware 1 ran
Middleware 2 ran
[2022-01-04 13:32:39 +1000] [45332] [ERROR] Exception occurred while handling uri: 'http://localhost:8000/'
Traceback (most recent call last):
  File "handle_request", line 62, in handle_request
    ...
  File "_run_request_middleware", line 26, in _run_request_middleware
    ...
  File "/home/ash/CODE/sanic/sanicpluginsframework/this.py", line 17, in my_middleware2
    raise SanicException()
sanic.exceptions.SanicException: None
Middleware 1 ran   #<--- Ran again!
Middleware 2 ran   #<--- Ran again! 
```

This is because app `handle_exception` does executes `_run_request_middleware` _again, after_ `handle_request` has already executed  `_run_request_middleware`.

Offending code is here:
https://github.com/sanic-org/sanic/blob/a7bc8b56bab01e066357e6dcc67c0dc9df864298/sanic/app.py#L786-L791

**Comment by ashleysommer** [comment]
Update:
I'm pretty sure this code was added last time this issue came up, to prevent this from happening:
https://github.com/sanic-org/sanic/blob/a7bc8b56bab01e066357e6dcc67c0dc9df864298/sanic/app.py#L1343-L1344

Not sure why I'm seeing this happening again. Might be something I'm looking at wrong in my testing.

**Comment by ahopkins** [comment]
Yeah, IIRC this was solved. :thinking: 

I am taking another look at this.

**Comment by ahopkins** [comment]
```python
@app.get("/")
async def handler(request: Request):
    return json({"foo": "bar"})


@app.on_request
async def first(_):
    print("first")


@app.on_request
async def second(_):
    print("second")
    1 / 0
```

```
first
second
[2022-01-04 09:43:10 +0200] [2605236] [ERROR] Exception occurred while handling uri: 'http://localhost:9999/'
Traceback (most recent call last):
  File "handle_request", line 62, in handle_request
    from sanic.asgi import ASGIApp
  File "_run_request_middleware", line 28, in _run_request_middleware
    from traceback import format_exc
  File "/tmp/p.py", line 19, in second
    1 / 0
ZeroDivisionError: division by zero
[2022-01-04 09:43:10 +0200] - (sanic.access)[INFO][127.0.0.1:39042]: GET http://localhost:9999/  500 467
```

This seems to be as expected.

**Comment by ashleysommer** [comment]
Yep, this can be closed. There was a problem with my test setup. As you see, my example code runs without issue.

**Comment by ahopkins** [comment]
Phew :relieved: 

I was worried this morning when I saw this issue in my inbox :laughing:
