### ISSUE TITLE
sanic-ext is not working

### ISSUE THREAD

**Issue by jonra1993** [sanic-org/sanic#2368]
**Describe the bug**
I am trying to run sanic and sanic-ext to check OpenAPI documentation. But the server shows an error message. If I remove sanic-ext, it runs correctly. I used sample hello world code from here https://sanic.dev/en/guide/getting-started.html#install

**Code snippet**
I installed sanic using poetry
`poetry add sanic sanic-ext`

**Expected behavior**
Run server and open documentation

**Environment (please complete the following information):**
 - Sanic (21.12.1)
-  Sanic-ext(21.12.1 and 21.12.3) 

**Additional context**
```
2022-01-11 12:48:29 -0500] [13508] [WARNING] Sanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.
[2022-01-11 12:48:29 -0500] [13508] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic/app.py", line 1204, in run
    serve_single(server_settings)
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic/server/runners.py", line 206, in serve_single
    serve(**server_settings)
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic/server/runners.py", line 120, in serve
    setup_ext(app)
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic/application/ext.py", line 23, in setup_ext
    sanic_ext = import_module("sanic_ext")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic_ext/__init__.py", line 1, in <module>
    from sanic_ext.bootstrap import Extend
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic_ext/bootstrap.py", line 14, in <module>
    from sanic_ext.extensions.http.extension import HTTPExtension
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic_ext/extensions/http/extension.py", line 4, in <module>
    from .methods import add_auto_handlers, add_http_methods
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic_ext/extensions/http/methods.py", line 11, in <module>
    from ..openapi import openapi
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic_ext/extensions/openapi/openapi.py", line 24, in <module>
    from sanic_ext.extensions.openapi.builders import (
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic_ext/extensions/openapi/builders.py", line 18, in <module>
    from .definitions import (
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic_ext/extensions/openapi/definitions.py", line 14, in <module>
    from .types import Definition, Schema
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic_ext/extensions/openapi/types.py", line 6, in <module>
    from typing import (
ImportError: cannot import name 'get_args' from 'typing' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py)
Traceback (most recent call last):
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/bin/sanic", line 8, in <module>
    sys.exit(main())
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic/__main__.py", line 12, in main
    cli.run()
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic/cli/app.py", line 77, in run
    app.run(**kwargs)
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic/app.py", line 1204, in run
    serve_single(server_settings)
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic/server/runners.py", line 206, in serve_single
    serve(**server_settings)
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic/server/runners.py", line 120, in serve
    setup_ext(app)
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic/application/ext.py", line 23, in setup_ext
    sanic_ext = import_module("sanic_ext")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic_ext/__init__.py", line 1, in <module>
    from sanic_ext.bootstrap import Extend
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic_ext/bootstrap.py", line 14, in <module>
    from sanic_ext.extensions.http.extension import HTTPExtension
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic_ext/extensions/http/extension.py", line 4, in <module>
    from .methods import add_auto_handlers, add_http_methods
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic_ext/extensions/http/methods.py", line 11, in <module>
    from ..openapi import openapi
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic_ext/extensions/openapi/openapi.py", line 24, in <module>
    from sanic_ext.extensions.openapi.builders import (
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic_ext/extensions/openapi/builders.py", line 18, in <module>
    from .definitions import (
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic_ext/extensions/openapi/definitions.py", line 14, in <module>
    from .types import Definition, Schema
  File "/Users/jona/Library/Caches/pypoetry/virtualenvs/testrasa-D3I8zhmW-py3.7/lib/python3.7/site-packages/sanic_ext/extensions/openapi/types.py", line 6, in <module>
    from typing import (
ImportError: cannot import name 'get_args' from 'typing' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py)
sys:1: RuntimeWarning: coroutine 'Loop.create_server' was never awaited
```

**Comment by ChihweiLHBird** [comment]
sanic-ext only officially support Python 3.8 or above. Can you try to upgrade the Python and try again?

**Comment by ahopkins** [comment]
Sanic Extensions requires Python 3.8+

https://sanic.dev/en/plugins/sanic-ext/getting-started.html#minimum-requirements

Unfortunately you will need to upgrade your Python version to use it.

**Comment by ahopkins** [comment]
Just curious, why 3.8 and not 3.9 or 3.10?

**Comment by jonra1993** [comment]
> Just curious, why 3.8 and not 3.9 or 3.10?

Thanks for asking @ahopkins. Currently, I am working on a project using Rasa, and sadly it is not 100% compatible with Sanic yet.

**Comment by ahopkins** [comment]
Makes sense. Thanks for sharing 😎
