### ISSUE TITLE
An exception is logged when listening on multiple sockets

### ISSUE THREAD

**Issue by jzombi** [sanic-org/sanic#2374]
The following exception is logged during startup when listening on multiple sockets (eg. unix, tcpip):

```
Task exception was never retrieved
future: <Task finished name='Task-4' coro=<runner() done, defined at test.py:19> exception=SanicException('Cannot run Sanic server without first running await server.startup()')>
Traceback (most recent call last):
  File "test.py", line 24, in runner
    await app_server.serve_forever()
  File "/home/janma/.pyenv/versions/3.8.12/lib/python3.8/site-packages/sanic/server/async_server.py", line 97, in serve_forever
    return self._serve(self.server.serve_forever)
  File "/home/janma/.pyenv/versions/3.8.12/lib/python3.8/site-packages/sanic/server/async_server.py", line 102, in _serve
    raise SanicException(
sanic.exceptions.SanicException: Cannot run Sanic server without first running await server.startup()
```

Apart from that log message, it seems to be working fine:

```
[2022-01-14 09:38:19 +0000] - (sanic.access)[INFO][UNKNOWN]: GET http://localhost/  200 4
[2022-01-14 09:38:21 +0000] - (sanic.access)[INFO][127.0.0.1:42958]: GET http://127.0.0.1:8765/  200 4
```

**Code snippet**
The following code is based on [Redirect HTTP to HTTPS How to](https://sanic.dev/en/guide/how-to/tls.html#redirect-http-to-https-with-certificate-requests-still-over-http):
```
import sanic


def main_page(request):
    return sanic.response.HTTPResponse(body='/ OK', status=200, headers=None, content_type='text/plain; charset=utf-8')


async def start(app, _):
    global unix_server
    unix_server = await unix_app.create_server(unix='/tmp/test.sock', return_asyncio_server=True)
    app.add_task(runner(unix_app, unix_server))


async def stop(app, _):
    if unix_server is not None:
        await unix_server.close()


async def runner(app, app_server):
    app.is_running = True
    try:
        app.signalize()
        app.finalize()
        await app_server.serve_forever()
    finally:
        app.is_running = False
        app.is_stopping = True


app = sanic.app.Sanic(name='app-tcpip')
app.add_route(handler=main_page, uri='/', methods=['GET'])

unix_app = sanic.app.Sanic(name='app-unix')
unix_app.add_route(handler=main_page, uri='/', methods=['GET'])

unix_server = None
app.register_listener(start, 'before_server_start')
app.register_listener(stop, 'before_server_stop')
app.run(host='127.0.0.1', port=8765, register_sys_signals=True)
```

**Environment:**
 - OS: Linux
 - Version: 21.12.1
 - Tested python versions: 3.7.12, 3.8.12

Please let me know if I'm doing something wrong.

**Comment by ahopkins** [comment]
You are doing the startup manually. So you just need to set the flag. After this 

```python
        app.signalize()
        app.finalize()
```

Add

```python
        app.state.is_started = True
```

**Comment by jzombi** [comment]
Thanks @ahopkins. Is it something that should be also added to the How to?

**Comment by ahopkins** [comment]
Probably, yes. Come 22.3 it will be MUCH easier: https://github.com/sanic-org/sanic/pull/2347.
