### ISSUE TITLE
Unable to exit normally when fast is set to True and use nextcord(discord.py).

### ISSUE THREAD

**Issue by tasuren** [sanic-org/sanic#2386]
**Describe the problem**
When I use `fast=True` on `sanic.Sanic` and use nextcord that forked discord.py and I stop program by Ctrl + C, I keep getting this error and can't quit.  
What could be the cause of this?
```python
[2022-01-22 08:41:01 +0900] [4349] [INFO] Received signal SIGTERM. Shutting down.
Traceback (most recent call last):
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>
Call stack:
[2022-01-22 08:41:01 +0900] [4348] [INFO] Received signal SIGTERM. Shutting down.
  File "/Users/tasuren/Documents/src/python/rt/rt-backend/main.py", line 63, in <module>
    app.run(**secret["app"])
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sanic/app.py", line 1206, in run
    serve_multiple(server_settings, workers)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sanic/server/runners.py", line 264, in serve_multiple
    process.start()
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sanic/server/runners.py", line 130, in serve
    loop.run_until_complete(app._server_event("init", "before"))
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sanic/server/runners.py", line 254, in <lambda>
    signal_func(SIGINT, lambda s, f: sig_handler(s, f))
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sanic/server/runners.py", line 250, in sig_handler
    logger.info("Received signal %s. Shutting down.", Signals(signal).name)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 665, in format
    record.asctime = self.formatTime(record, self.datefmt)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 602, in formatTime
    s = time.strftime(datefmt, ct)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sanic/server/runners.py", line 255, in <lambda>
    signal_func(SIGTERM, lambda s, f: sig_handler(s, f))
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sanic/server/runners.py", line 250, in sig_handler
    logger.info("Received signal %s. Shutting down.", Signals(signal).name)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 665, in format
    record.asctime = self.formatTime(record, self.datefmt)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 600, in formatTime
    ct = self.converter(record.created)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sanic/server/runners.py", line 255, in <lambda>
    signal_func(SIGTERM, lambda s, f: sig_handler(s, f))
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sanic/server/runners.py", line 252, in sig_handler
    os.kill(process.pid, SIGTERM)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sanic/server/runners.py", line 255, in <lambda>
    signal_func(SIGTERM, lambda s, f: sig_handler(s, f))
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sanic/server/runners.py", line 250, in sig_handler
    logger.info("Received signal %s. Shutting down.", Signals(signal).name)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 665, in format
    record.asctime = self.formatTime(record, self.datefmt)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 600, in formatTime
    ct = self.converter(record.created)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sanic/server/runners.py", line 255, in <lambda>
    signal_func(SIGTERM, lambda s, f: sig_handler(s, f))
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sanic/server/runners.py", line 250, in sig_handler
    logger.info("Received signal %s. Shutting down.", Signals(signal).name)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1577, in _log
    fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sanic/server/runners.py", line 255, in <lambda>
    signal_func(SIGTERM, lambda s, f: sig_handler(s, f))
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sanic/server/runners.py", line 250, in sig_handler
    logger.info("Received signal %s. Shutting down.", Signals(signal).name)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 665, in format
    record.asctime = self.formatTime(record, self.datefmt)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 600, in formatTime
    ct = self.converter(record.created)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sanic/server/runners.py", line 255, in <lambda>
    signal_func(SIGTERM, lambda s, f: sig_handler(s, f))
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sanic/server/runners.py", line 250, in sig_handler
    logger.info("Received signal %s. Shutting down.", Signals(signal).name)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/logging/__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sanic/server/runners.py", line 255, in <lambda>
    signal_func(SIGTERM, lambda s, f: sig_handler(s, f))
  File "/Users/tasuren/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sanic/server/runners.py", line 250, in sig_handler
    logger.info("Received signal %s. Shutting down.", Signals(signal).name)
Message: 'Received signal %s. Shutting down.'
Arguments: ('SIGTERM',)
[2022-01-22 08:41:01 +0900] [4351] [INFO] Received signal SIGTERM. Shutting down.
```

**Code snippet**
I'm not sure where to point you, so I've included the URL of the repository where all the code is located.  
https://github.com/RT-Team/rt-backend

**Expected behavior**
I want to make sure that it exits normally.

**Environment (please complete the following information):**
```
  ┌──────────────────────────────────────────────────────────────┐
  │                        Sanic v21.12.1                        │
  │                Goin' Fast @ http://0.0.0.0:80                │
  ├───────────────────────┬──────────────────────────────────────┤
  │                       │     mode: production, single worker  │
  │     ▄███ █████ ██     │   server: sanic                      │
  │    ██                 │   python: 3.9.7                      │
  │     ▀███████ ███▄     │ platform: macOS-12.1-arm64-arm-64bit │
  │                 ██    │ packages: sanic-routing==0.7.2       │
  │    ████ ████████▀     │                                      │
  │                       │                                      │
  │ Build Fast. Run Fast. │                                      │
  └───────────────────────┴──────────────────────────────────────┘
```

**Comment by tasuren** [comment]
I disabled the Bot and it worked.
So, should I close the issue?

**Comment by tasuren** [comment]
Also, bot will boot by [this code](https://github.com/RT-Team/rt-backend/blob/2fdf2cd878b8659fb22a0d52da98f2f51f18770c/backend/backend.py#L88).

**Comment by ahopkins** [comment]
What kind of logging setup are you using? If I had to guess, it seems like you are doing something to interfere with the normal standard lib `logging`. Are you running Discord off the main process or every worker process? Perhaps your discord app cannot function with multiprocessing.

**Comment by tasuren** [comment]
I running bot on event loop that is same as sanic.  
And I am running it only on one Worker.

**Comment by ahopkins** [comment]
https://github.com/RT-Team/rt-backend/blob/2fdf2cd878b8659fb22a0d52da98f2f51f18770c/backend/backend.py#L76

Looks like on every worker. Use `main_process_start` and `main_process_stop` if you want to limit it to only one of many.

**Comment by tasuren** [comment]
I see.
I would like to run the Bot in a separate process.
Thank you very much for your answer.

**Comment by ahopkins** [comment]
You should use the main process listeners then.
