### ISSUE TITLE
Windows: no running event loop as of 22.3.0

### ISSUE THREAD

**Issue by jamesstidard** [sanic-org/sanic#2422]
**Describe the bug**
Hey, heads up, after updating to `22.3.0` a sanic server no longer starts on my Windows machine. Instead raises a `RuntimeError: no running event loop`. Seen this on two separate Windows machines so far.

**Code snippet**
```python
# main.py
import sanic

app = sanic.Sanic("foo")

@app.get("/bar")
async def _(request):
    return sanic.response.text("buzz")

app.run(host="127.0.0.1", port=1337, access_log=False)
```

```console
$ pipenv run python main.py
[2022-04-04 13:33:34 +0100] [14080] [INFO] 
  ┌─────────────────────────────────────────────────────────────┐
  │                        Sanic v22.3.0                        │
  │               Goin' Fast @ http://0.0.0.0:1337              │
  ├───────────────────────┬─────────────────────────────────────┤
  │                       │     mode: production, single worker │
  │     ▄███ █████ ██     │   server: sanic                     │
  │    ██                 │   python: 3.9.2                     │
  │     ▀███████ ███▄     │ platform: Windows-10-10.0.22000-SP0 │
  │                 ██    │ packages: sanic-routing==22.3.0     │
  │    ████ ████████▀     │                                     │
  │                       │                                     │
  │ Build Fast. Run Fast. │                                     │
  └───────────────────────┴─────────────────────────────────────┘

[2022-04-04 13:33:34 +0100] [14080] [WARNING] Sanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.
[2022-04-04 13:33:34 +0100] [14080] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "C:\Users\James\.virtualenvs\test-lP8LJtvX\lib\site-packages\sanic\mixins\runner.py", line 578, in serve
    serve_single(primary_server_info.settings)
  File "C:\Users\James\.virtualenvs\test-lP8LJtvX\lib\site-packages\sanic\server\runners.py", line 206, in serve_single
    serve(**server_settings)
  File "C:\Users\James\.virtualenvs\test-lP8LJtvX\lib\site-packages\sanic\server\runners.py", line 146, in serve
    ctrlc_workaround_for_windows(app)
  File "C:\Users\James\.virtualenvs\test-lP8LJtvX\lib\site-packages\sanic\compat.py", line 91, in ctrlc_workaround_for_windows
    app.add_task(stay_active)
  File "C:\Users\James\.virtualenvs\test-lP8LJtvX\lib\site-packages\sanic\app.py", line 1217, in add_task
    loop = self.loop  # Will raise SanicError if loop is not started
  File "C:\Users\James\.virtualenvs\test-lP8LJtvX\lib\site-packages\sanic\app.py", line 255, in loop
    return get_running_loop()
RuntimeError: no running event loop
Traceback (most recent call last):
  File "C:\Users\James\Desktop\test\main.py", line 9, in <module>
    app.run(host='0.0.0.0', port=1337, access_log=False)
  File "C:\Users\James\.virtualenvs\test-lP8LJtvX\lib\site-packages\sanic\mixins\runner.py", line 145, in run
    self.class.serve(primary=self)  # type: ignore
  File "C:\Users\James\.virtualenvs\test-lP8LJtvX\lib\site-packages\sanic\mixins\runner.py", line 578, in serve
[2022-04-04 13:40:57 +0100] [22748] [WARNING] Sanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.
[2022-04-04 13:40:57 +0100] [22748] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "C:\Users\James\.virtualenvs\test-lP8LJtvX\lib\site-packages\sanic\mixins\runner.py", line 578, in serve
    serve_single(primary_server_info.settings)
  File "C:\Users\James\.virtualenvs\test-lP8LJtvX\lib\site-packages\sanic\server\runners.py", line 206, in serve_single
    serve(**server_settings)
  File "C:\Users\James\.virtualenvs\test-lP8LJtvX\lib\site-packages\sanic\server\runners.py", line 146, in serve
    ctrlc_workaround_for_windows(app)
  File "C:\Users\James\.virtualenvs\test-lP8LJtvX\lib\site-packages\sanic\compat.py", line 91, in ctrlc_workaround_for_windows
    app.add_task(stay_active)
  File "C:\Users\James\.virtualenvs\test-lP8LJtvX\lib\site-packages\sanic\app.py", line 1217, in add_task
    loop = self.loop  # Will raise SanicError if loop is not started
  File "C:\Users\James\.virtualenvs\test-lP8LJtvX\lib\site-packages\sanic\app.py", line 255, in loop
    return get_running_loop()
RuntimeError: no running event loop
Traceback (most recent call last):
  File "C:\Users\James\Desktop\test\main.py", line 9, in <module>
    app.run(port=1337, access_log=False)
  File "C:\Users\James\.virtualenvs\test-lP8LJtvX\lib\site-packages\sanic\mixins\runner.py", line 145, in run
    self.class.serve(primary=self)  # type: ignore
  File "C:\Users\James\.virtualenvs\test-lP8LJtvX\lib\site-packages\sanic\mixins\runner.py", line 578, in serve
    serve_single(primary_server_info.settings)
  File "C:\Users\James\.virtualenvs\test-lP8LJtvX\lib\site-packages\sanic\server\runners.py", line 206, in serve_single
    serve(**server_settings)
  File "C:\Users\James\.virtualenvs\test-lP8LJtvX\lib\site-packages\sanic\server\runners.py", line 146, in serve
    ctrlc_workaround_for_windows(app)
  File "C:\Users\James\.virtualenvs\test-lP8LJtvX\lib\site-packages\sanic\compat.py", line 91, in ctrlc_workaround_for_windows
    app.add_task(stay_active)
  File "C:\Users\James\.virtualenvs\test-lP8LJtvX\lib\site-packages\sanic\app.py", line 1217, in add_task
    loop = self.loop  # Will raise SanicError if loop is not started
  File "C:\Users\James\.virtualenvs\test-lP8LJtvX\lib\site-packages\sanic\app.py", line 255, in loop
    return get_running_loop()
RuntimeError: no running event loop
```

**Environment (please complete the following information):**
 - OS: Windows 11 Pro
 - Version 10.0.22000 build 22000
 - Python: 3.9.2

**Comment by jekel** [comment]
Have same problem on windows system, python 3.9.10.

**Comment by pulpe** [comment]
Same here - Windows 10 Pro, Python 3.10.4

**Comment by beliboba** [comment]
same

**Comment by beliboba** [comment]
I added 
`if __name__ == '__main__':
    app.run(port=5000)`
   and this worked for me

**Comment by kevinkelin** [comment]
I edit sanic source code  sanic/app.py def loop(self) function 
```python
    @property
    def loop(self):
        """
        Synonymous with asyncio.get_event_loop().

        .. note::

            Only supported when using the `app.run` method.
        """
        if self.state.stage is ServerStage.STOPPED and self.asgi is False:
            raise SanicException(
                "Loop can only be retrieved after the app has started "
                "running. Not supported with `create_server` function"
            )
        # return get_running_loop()
        try:
            return get_running_loop()  # here will raise in windows 
        except RuntimeError:
            return asyncio.get_event_loop()
```

and this worked for me for local develop

**Comment by baikeh** [comment]
there is a bug in the latest release, so you can try the previous release `pip install sanic==20.12.6` if you no need the features of the latest release

**Comment by ahopkins** [comment]
v22.3.1 should resolve this and has been released. Feedback :+1: or :-1: would be appreciated.

**Comment by ljd1995** [comment]
> v22.3.1 should resolve this and has been released. Feedback 👍 or 👎 would be appreciated.

It maybe not solve,please check

INFO:sanic.root:
  ┌───────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.3.1                                 │
  │                        Goin' Fast @ http://0.0.0.0:8000                       │
  ├───────────────────────┬───────────────────────────────────────────────────────┤
  │                       │        mode: debug, single worker                     │
  │     ▄███ █████ ██     │      server: sanic                                    │
  │    ██                 │      python: 3.9.12                                   │
  │     ▀███████ ███▄     │    platform: Windows-10-10.0.22000-SP0                │
  │                 ██    │ auto-reload: enabled                                  │
  │    ████ ████████▀     │    packages: sanic-routing==22.3.0, sanic-ext==22.3.0 │
  │                       │                                                       │
  │ Build Fast. Run Fast. │                                                       │
  └───────────────────────┴───────────────────────────────────────────────────────┘

[2022-04-19 09:14:32 +0800] [2412] [INFO] Sanic Extensions:
INFO:sanic.root:Sanic Extensions:
[2022-04-19 09:14:32 +0800] [2412] [INFO]   > http
INFO:sanic.root:  > http
[2022-04-19 09:14:32 +0800] [2412] [INFO]   > openapi [http://0.0.0.0:8000/docs]
INFO:sanic.root:  > openapi [http://0.0.0.0:8000/docs]
[2022-04-19 09:14:32 +0800] [2412] [INFO]   > injection [0 added]
INFO:sanic.root:  > injection [0 added]
[2022-04-19 09:14:32 +0800] [2412] [DEBUG] Dispatching signal: server.init.before
DEBUG:sanic.root:Dispatching signal: server.init.before
[2022-04-19 09:14:32 +0800] [2412] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\app.py", line 1140, in _listener
    maybe_coro = listener(app)  # type: ignore
TypeError: build_spec() missing 1 required positional argument: 'loop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\mixins\runner.py", line 578, in serve
    serve_single(primary_server_info.settings)
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\server\runners.py", line 206, in serve_single
    serve(**server_settings)
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\server\runners.py", line 130, in serve
    loop.run_until_complete(app._server_event("init", "before"))
  File "G:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\app.py", line 1581, in _server_event
    await self.dispatch(
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\signals.py", line 193, in dispatch
    return await dispatch
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\signals.py", line 163, in _dispatch
    retval = await maybe_coroutine
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\app.py", line 1142, in _listener
    maybe_coro = listener(app, loop)  # type: ignore
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic_ext\extensions\openapi\blueprint.py", line 142, in build_spec
    operation.parameter(
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic_ext\extensions\openapi\builders.py", line 99, in parameter
    Parameter.make(name, schema, location, **kwargs)
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic_ext\extensions\openapi\definitions.py", line 236, in make
    return Parameter(name, Schema.make(schema), location, **kwargs)
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic_ext\extensions\openapi\types.py", line 182, in make
    return Object.make(value, **kwargs)
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic_ext\extensions\openapi\types.py", line 279, in make
    {k: Schema.make(v) for k, v in _properties(value).items()},
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic_ext\extensions\openapi\types.py", line 319, in _properties
    for k, v in {**get_type_hints(cls), **fields}.items()
  File "G:\Python39\lib\typing.py", line 1454, in get_type_hints
    for name, value in ann.items():
AttributeError: 'getset_descriptor' object has no attribute 'items'
ERROR:sanic.error:Experienced exception while trying to serve
Traceback (most recent call last):
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\app.py", line 1140, in _listener
    maybe_coro = listener(app)  # type: ignore
TypeError: build_spec() missing 1 required positional argument: 'loop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\mixins\runner.py", line 578, in serve
    serve_single(primary_server_info.settings)
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\server\runners.py", line 206, in serve_single
    serve(**server_settings)
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\server\runners.py", line 130, in serve
    loop.run_until_complete(app._server_event("init", "before"))
  File "G:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\app.py", line 1581, in _server_event
    await self.dispatch(
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\signals.py", line 193, in dispatch
    return await dispatch
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\signals.py", line 163, in _dispatch
    retval = await maybe_coroutine
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\app.py", line 1142, in _listener
    maybe_coro = listener(app, loop)  # type: ignore
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic_ext\extensions\openapi\blueprint.py", line 142, in build_spec
    operation.parameter(
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic_ext\extensions\openapi\builders.py", line 99, in parameter
    Parameter.make(name, schema, location, **kwargs)
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic_ext\extensions\openapi\definitions.py", line 236, in make
    return Parameter(name, Schema.make(schema), location, **kwargs)
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic_ext\extensions\openapi\types.py", line 182, in make
    return Object.make(value, **kwargs)
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic_ext\extensions\openapi\types.py", line 279, in make
    {k: Schema.make(v) for k, v in _properties(value).items()},
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic_ext\extensions\openapi\types.py", line 319, in _properties
    for k, v in {**get_type_hints(cls), **fields}.items()
  File "G:\Python39\lib\typing.py", line 1454, in get_type_hints
    for name, value in ann.items():
AttributeError: 'getset_descriptor' object has no attribute 'items'
Traceback (most recent call last):
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\app.py", line 1140, in _listener
    maybe_coro = listener(app)  # type: ignore
TypeError: build_spec() missing 1 required positional argument: 'loop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\95250\OneDrive\space\space-devops-operation\app.py", line 7, in <module>
    app.run(auto_reload=True, host="0.0.0.0", port=8000, access_log=True, debug=True, workers=1)
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\mixins\runner.py", line 145, in run
    self.__class__.serve(primary=self)  # type: ignore
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\mixins\runner.py", line 578, in serve
    serve_single(primary_server_info.settings)
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\server\runners.py", line 206, in serve_single
    serve(**server_settings)
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\server\runners.py", line 130, in serve
    loop.run_until_complete(app._server_event("init", "before"))
  File "G:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\app.py", line 1581, in _server_event
    await self.dispatch(
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\signals.py", line 193, in dispatch
    return await dispatch
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\signals.py", line 163, in _dispatch
    retval = await maybe_coroutine
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic\app.py", line 1142, in _listener
    maybe_coro = listener(app, loop)  # type: ignore
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic_ext\extensions\openapi\blueprint.py", line 142, in build_spec
    operation.parameter(
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic_ext\extensions\openapi\builders.py", line 99, in parameter
    Parameter.make(name, schema, location, **kwargs)
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic_ext\extensions\openapi\definitions.py", line 236, in make
    return Parameter(name, Schema.make(schema), location, **kwargs)
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic_ext\extensions\openapi\types.py", line 182, in make
    return Object.make(value, **kwargs)
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic_ext\extensions\openapi\types.py", line 279, in make
    {k: Schema.make(v) for k, v in _properties(value).items()},
  File "C:\Users\95250\.virtualenvs\space-devops-operation-ljD-TcsW\lib\site-packages\sanic_ext\extensions\openapi\types.py", line 319, in _properties
    for k, v in {**get_type_hints(cls), **fields}.items()
  File "G:\Python39\lib\typing.py", line 1454, in get_type_hints
    for name, value in ann.items():
AttributeError: 'getset_descriptor' object has no attribute 'items'
sys:1: RuntimeWarning: coroutine 'BaseEventLoop.create_server' was never awaited

**Comment by ahopkins** [comment]
It is this issue: https://github.com/sanic-org/sanic-ext/issues/70

Patch coming later today

**Comment by ljd1995** [comment]
> It is this issue: [sanic-org/sanic-ext#70](https://github.com/sanic-org/sanic-ext/issues/70)
> 
> Patch coming later today

when upgrade sanic-ext 22.3.1, it is ok
