### ISSUE TITLE
TypeError: build_spec() missing 1 required positional argument: 'loop'

### ISSUE THREAD

**Issue by Basit-qc** [sanic-org/sanic#2431]
**Describe the bug**
- Getting `TypeError: build_spec() missing 1 required positional argument: 'loop'` upon running the server
- sanic-ext is installed

**Code snippet**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sanic/app.py", line 1140, in _listener
    maybe_coro = listener(app)  # type: ignore
TypeError: build_spec() missing 1 required positional argument: 'loop'
```

**Additonal Logs**
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/sanic/server/runners.py", line 130, in serve
    loop.run_until_complete(app._server_event("init", "before"))
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.9/site-packages/sanic/app.py", line 1581, in _server_event
    await self.dispatch(
  File "/usr/local/lib/python3.9/site-packages/sanic/signals.py", line 193, in dispatch
    return await dispatch
  File "/usr/local/lib/python3.9/site-packages/sanic/signals.py", line 163, in _dispatch
    retval = await maybe_coroutine
  File "/usr/local/lib/python3.9/site-packages/sanic/app.py", line 1142, in _listener
    maybe_coro = listener(app, loop)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/sanic_ext/extensions/openapi/blueprint.py", line 142, in build_spec
    operation.parameter(
  File "/usr/local/lib/python3.9/site-packages/sanic_ext/extensions/openapi/builders.py", line 99, in parameter
    Parameter.make(name, schema, location, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sanic_ext/extensions/openapi/definitions.py", line 236, in make
    return Parameter(name, Schema.make(schema), location, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sanic_ext/extensions/openapi/types.py", line 182, in make
    return Object.make(value, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sanic_ext/extensions/openapi/types.py", line 279, in make
    {k: Schema.make(v) for k, v in _properties(value).items()},
  File "/usr/local/lib/python3.9/site-packages/sanic_ext/extensions/openapi/types.py", line 319, in _properties
    for k, v in {**get_type_hints(cls), **fields}.items()
  File "/usr/local/lib/python3.9/typing.py", line 1454, in get_type_hints
    for name, value in ann.items():
AttributeError: 'getset_descriptor' object has no attribute 'items'

```

**Environment (please complete the following information):**
 - Version [e.g. 22.3.1]

**Additional context**
Without sanic-ext package, it works fine but then I have CORS issues.

**Comment by prryplatypus** [comment]
Could you provide a **code snippet** that this issue can be reproduced with? I am unable to reproduce this error with this one (`sanic-ext` gets enabled automatically):
```py
from sanic import Sanic, text

app = Sanic("my_app")

@app.get("/ping")
async def ping(request):
    return text("pong")

app.run(host="0.0.0.0", port=8000)
```

In addition, could you please let us know **what versions** you're seeing this with? You can see the versions here:
![Sanic's MOTD](https://i.imgur.com/dq90fLu.png)

**Comment by ahopkins** [comment]
I think this is a version mismatch between 21.12 and 22.3.

**Comment by ahopkins** [comment]
I am looking into this now using:

![image](https://user-images.githubusercontent.com/166269/163874490-07ad4f8c-67f4-46ac-ba5d-c4efd438eb03.png)

Trying to figure out the minimal example that causes this though.

**Comment by ahopkins** [comment]
Reproduced with a dynamic path:

```python
from sanic import Sanic, text

app = Sanic("my_app")


@app.get("/ping/<ping>")
async def ping(request):
    return text("pong")


app.run(dev=True)
```
