### ISSUE TITLE
Error reporting without annotation is very unfriendly.

### ISSUE THREAD

**Issue by zhuangchaoxi** [sanic-org/sanic#2433]
**Describe the bug**
A clear and concise description of what the bug is, make sure to paste any exceptions and tracebacks.
Error reporting without annotation is very unfriendly.

**Code snippet**
Relevant source code, make sure to remove what is not necessary.
curves = Blueprint("curves", url_prefix="/curves")

@curves.get("/<curve_id>")
async def curve_data(request, curve_id):
    return json({"data": "ok"})

**Expected behavior**
```
Traceback (most recent call last):
  File "/Users/liuyahui/miniconda3/envs/volmarker_service/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/liuyahui/miniconda3/envs/volmarker_service/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/liuyahui/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/liuyahui/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/Users/liuyahui/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/Users/liuyahui/miniconda3/envs/volmarker_service/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/liuyahui/miniconda3/envs/volmarker_service/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/liuyahui/miniconda3/envs/volmarker_service/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/liuyahui/codes/tadsec/vol-marker-service/main.py", line 7, in <module>
    app.start(host="0.0.0.0", port=5000)
  File "/Users/liuyahui/codes/tadsec/vol-marker-service/vol_marker_service/app.py", line 89, in start
    app.run(host=host, port=port, **kwargs_)
  File "/Users/liuyahui/miniconda3/envs/volmarker_service/lib/python3.9/site-packages/sanic/mixins/runner.py", line 145, in run
    self.__class__.serve(primary=self)  # type: ignore
  File "/Users/liuyahui/miniconda3/envs/volmarker_service/lib/python3.9/site-packages/sanic/mixins/runner.py", line 578, in serve
    serve_single(primary_server_info.settings)
  File "/Users/liuyahui/miniconda3/envs/volmarker_service/lib/python3.9/site-packages/sanic/server/runners.py", line 206, in serve_single
    serve(**server_settings)
  File "/Users/liuyahui/miniconda3/envs/volmarker_service/lib/python3.9/site-packages/sanic/server/runners.py", line 130, in serve
    loop.run_until_complete(app._server_event("init", "before"))
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/Users/liuyahui/miniconda3/envs/volmarker_service/lib/python3.9/site-packages/sanic/app.py", line 1575, in _server_event
    await self.dispatch(
  File "/Users/liuyahui/miniconda3/envs/volmarker_service/lib/python3.9/site-packages/sanic/signals.py", line 193, in dispatch
    return await dispatch
  File "/Users/liuyahui/miniconda3/envs/volmarker_service/lib/python3.9/site-packages/sanic/signals.py", line 163, in _dispatch
    retval = await maybe_coroutine
  File "/Users/liuyahui/miniconda3/envs/volmarker_service/lib/python3.9/site-packages/sanic/app.py", line 1136, in _listener
    maybe_coro = listener(app, loop)  # type: ignore
  File "/Users/liuyahui/miniconda3/envs/volmarker_service/lib/python3.9/site-packages/sanic_ext/extensions/openapi/blueprint.py", line 137, in build_spec
    operation.parameter(
  File "/Users/liuyahui/miniconda3/envs/volmarker_service/lib/python3.9/site-packages/sanic_ext/extensions/openapi/builders.py", line 93, in parameter
    Parameter.make(name, schema, location, **kwargs)
  File "/Users/liuyahui/miniconda3/envs/volmarker_service/lib/python3.9/site-packages/sanic_ext/extensions/openapi/definitions.py", line 236, in make
    return Parameter(name, Schema.make(schema), location, **kwargs)
  File "/Users/liuyahui/miniconda3/envs/volmarker_service/lib/python3.9/site-packages/sanic_ext/extensions/openapi/types.py", line 174, in make
    return Object.make(value, **kwargs)
  File "/Users/liuyahui/miniconda3/envs/volmarker_service/lib/python3.9/site-packages/sanic_ext/extensions/openapi/types.py", line 271, in make
    {k: Schema.make(v) for k, v in _properties(value).items()},
  File "/Users/liuyahui/miniconda3/envs/volmarker_service/lib/python3.9/site-packages/sanic_ext/extensions/openapi/types.py", line 311, in _properties
    for k, v in {**get_type_hints(cls), **fields}.items()
  File "/Users/liuyahui/miniconda3/envs/volmarker_service/lib/python3.9/typing.py", line 1454, in get_type_hints
    for name, value in ann.items():
AttributeError: 'getset_descriptor' object has no attribute 'items'
```

**Environment (please complete the following information):**
 - Version [e.g. 0.8.3]

**Additional context**

**Comment by prryplatypus** [comment]
This is an issue with sanic-ext. See https://github.com/sanic-org/sanic-ext/issues/70 :)

**Comment by ahopkins** [comment]
Upgrade sanic extensions will resolve this.
