### ISSUE TITLE
`protocol.connection_task uncaught` when using `sanic.Sanic.create_server`

### ISSUE THREAD

**Issue by jamesstidard** [sanic-org/sanic#2460]
**Describe the bug**
I'm trying to use sanic as a ad-hoc server to temporarily run in the background of another application. For this I'm using `sanic.Sanic.create_server`. The server appears to start up, but on a http request it dumps error logs, and the http request is dropped.

```python
import asyncio

from sanic import Sanic
from sanic.response import text


async def main():
    app = Sanic("example", configure_logging=False)

    @app.route("/")
    async def _(request):
        return text("Hi.")

    await app.create_server(
        host="localhost",
        port=8000,
        access_log=False,
        return_asyncio_server=True,
    )

    await asyncio.sleep(60)


if __name__ == "__main__":
    asyncio.run(main())
```

```console
Sanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.
protocol.connection_task uncaught
Traceback (most recent call last):
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/server/protocols/http_protocol.py", line 101, in connection_task
    await self.app.dispatch(
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 193, in dispatch
    return await dispatch
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 131, in _dispatch
    group, handlers, params = self.get(event, condition=condition)
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 93, in get
    group, param_basket = self.find_route(
TypeError: 'NoneType' object is not callable
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<HttpProtocol.connection_task() done, defined at /tmp/src/.venv/lib/python3.8/site-packages/sanic/server/protocols/http_protocol.py:92> exception=TypeError("'NoneType' object is not callable")>
Traceback (most recent call last):
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/server/protocols/http_protocol.py", line 130, in connection_task
    await self.app.dispatch(
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 193, in dispatch
    return await dispatch
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 131, in _dispatch
    group, handlers, params = self.get(event, condition=condition)
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 93, in get
    group, param_basket = self.find_route(
TypeError: 'NoneType' object is not callable
protocol.connection_task uncaught
Traceback (most recent call last):
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/server/protocols/http_protocol.py", line 101, in connection_task
    await self.app.dispatch(
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 193, in dispatch
    return await dispatch
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 131, in _dispatch
    group, handlers, params = self.get(event, condition=condition)
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 93, in get
    group, param_basket = self.find_route(
TypeError: 'NoneType' object is not callable
Task exception was never retrieved
future: <Task finished name='Task-7' coro=<HttpProtocol.connection_task() done, defined at /tmp/src/.venv/lib/python3.8/site-packages/sanic/server/protocols/http_protocol.py:92> exception=TypeError("'NoneType' object is not callable")>
Traceback (most recent call last):
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/server/protocols/http_protocol.py", line 130, in connection_task
    await self.app.dispatch(
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 193, in dispatch
    return await dispatch
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 131, in _dispatch
    group, handlers, params = self.get(event, condition=condition)
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 93, in get
    group, param_basket = self.find_route(
TypeError: 'NoneType' object is not callable
protocol.connection_task uncaught
Traceback (most recent call last):
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/server/protocols/http_protocol.py", line 101, in connection_task
    await self.app.dispatch(
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 193, in dispatch
    return await dispatch
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 131, in _dispatch
    group, handlers, params = self.get(event, condition=condition)
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 93, in get
    group, param_basket = self.find_route(
TypeError: 'NoneType' object is not callable
Task exception was never retrieved
future: <Task finished name='Task-9' coro=<HttpProtocol.connection_task() done, defined at /tmp/src/.venv/lib/python3.8/site-packages/sanic/server/protocols/http_protocol.py:92> exception=TypeError("'NoneType' object is not callable")>
Traceback (most recent call last):
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/server/protocols/http_protocol.py", line 130, in connection_task
    await self.app.dispatch(
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 193, in dispatch
    return await dispatch
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 131, in _dispatch
    group, handlers, params = self.get(event, condition=condition)
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 93, in get
    group, param_basket = self.find_route(
TypeError: 'NoneType' object is not callable
protocol.connection_task uncaught
Traceback (most recent call last):
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/server/protocols/http_protocol.py", line 101, in connection_task
    await self.app.dispatch(
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 193, in dispatch
    return await dispatch
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 131, in _dispatch
    group, handlers, params = self.get(event, condition=condition)
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 93, in get
    group, param_basket = self.find_route(
TypeError: 'NoneType' object is not callable
Task exception was never retrieved
future: <Task finished name='Task-11' coro=<HttpProtocol.connection_task() done, defined at /tmp/src/.venv/lib/python3.8/site-packages/sanic/server/protocols/http_protocol.py:92> exception=TypeError("'NoneType' object is not callable")>
Traceback (most recent call last):
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/server/protocols/http_protocol.py", line 130, in connection_task
    await self.app.dispatch(
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 193, in dispatch
    return await dispatch
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 131, in _dispatch
    group, handlers, params = self.get(event, condition=condition)
  File "/tmp/src/.venv/lib/python3.8/site-packages/sanic/signals.py", line 93, in get
    group, param_basket = self.find_route(
TypeError: 'NoneType' object is not callable
```

**Environment (please complete the following information):**
 - OS: macOS 12.4
 - Version 22.3.2 (also tried on 21.x)

**Additional context**
This had worked in the past. And by the past, I mean like 3-4 years ago. II'm going back to a old project and updating it.

**Comment by sjsadowski** [comment]
There's a lot to crack here, but Sanic from 2018, especially before the cleanup and the switch to CalVer is a very different beast from the current version. It is unlikely you'll simply be able to swap anything, especially a 0.x version of Sanic for anything 19.x or newer. Please take a look at the docs, give refactoring using the modern sanic codebase a whirl, and then swing on over to the [forums](https://community.sanic.dev) or [Discord](https://discord.gg/FARQzAEMAA) where we can help you out.

**Comment by ahopkins** [comment]
@jamesstidard You should take a look at the example here: https://github.com/sanic-org/sanic/blob/main/examples/run_async.py

For a lot of reasons, you should try to avoid the `create_server` pattern. Without very close attention to low-level details that is a trap. There are a lot of Sanic features that will simply not work without proper implementation on your own (listeners for example). The most obvious is that without taking certain steps that are required at run time, Sanic will fail to load at all.

The reason you are seeing this is because Sanic's router needs to perform some startup operations. We tried to make it easier by bundling _some_ of the required startup operations in `app.startup`, but that will not contain and do everything.

As @sjsadowski mentioned, please feel free to contact us on the forums or Discord for more discussion.
