### ISSUE TITLE
No module named 'sanic.worker'

### ISSUE THREAD

**Issue by ruifan831** [sanic-org/sanic#2500]
**Describe the bug**
Trying to use gunicorn to run sanic app, but got error below
```
bash-3.1# gunicorn myapp:app --bind 127.0.0.1:8089 --worker-class sanic.worker.GunicornWorker

Error: class uri 'sanic.worker.GunicornWorker' invalid or not found:

[Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gunicorn/util.py", line 99, in load_class
    mod = importlib.import_module('.'.join(components))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sanic.worker'
]
```

**Comment by ahopkins** [comment]
https://sanic.dev/en/guide/release-notes/v22.3.html#%F0%9F%9A%A8-breaking-change-sanic-worker-gunicornworker-has-been-removed

**Comment by yayaQAQ** [comment]
As stated in the documentation above, sanic.worker.GunicornWorker has been removed, we should use uvicorn

```pip install uvicorn```
then
```gunicorn path.to.sanic:app -k uvicorn.workers.UvicornWorker```
