### ISSUE TITLE
Strange Error after last update

### ISSUE THREAD

**Issue by vgoklani** [sanic-org/sanic#2528]
Seeing a strange error our sanic logs after updating sanic, but not sure what this means or how to fix this:

    [2022-08-16 21:22:56 +0000] [2201] [ERROR] protocol.connection_task uncaught
    Traceback (most recent call last):
      File "http1_request_header", line 41, in http1_request_header
        :raises ServerError:
    Exception

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/sanic/http/http1.py", line 123, in http1
        await self.http1_request_header()
      File "http1_request_header", line 57, in http1_request_header
        __slots__ = [
    sanic.exceptions.BadRequest: Bad Request

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/sanic/request.py", line 145, in __init__
        self._parsed_url = parse_url(url_bytes)
      File "httptools/parser/url_parser.pyx", line 105, in httptools.parser.url_parser.parse_url
    httptools.parser.errors.HttpParserInvalidURLError: invalid url b'sip:nm'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "connection_task", line 15, in connection_task
        from asyncio import CancelledError
      File "/opt/conda/lib/python3.9/site-packages/sanic/http/http1.py", line 149, in http1
        await self.error_response(e)
      File "/opt/conda/lib/python3.9/site-packages/sanic/http/http1.py", line 425, in error_response
        self.create_empty_request()
      File "/opt/conda/lib/python3.9/site-packages/sanic/http/http1.py", line 437, in create_empty_request
        self.request = self.protocol.request_class(
      File "/opt/conda/lib/python3.9/site-packages/sanic/request.py", line 147, in __init__
        raise BadURL(f"Bad URL: {url_bytes.decode()}")
    sanic.exceptions.BadURL: Bad URL: sip:nm
    2201 - 2022-08-16 21:22:56,327 - sanic.error - ERROR - protocol.connection_task uncaught
    Traceback (most recent call last):
      File "http1_request_header", line 41, in http1_request_header
        :raises ServerError:
    Exception

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/sanic/http/http1.py", line 123, in http1
        await self.http1_request_header()
      File "http1_request_header", line 57, in http1_request_header
        __slots__ = [
    sanic.exceptions.BadRequest: Bad Request

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/sanic/request.py", line 145, in __init__
        self._parsed_url = parse_url(url_bytes)
      File "httptools/parser/url_parser.pyx", line 105, in httptools.parser.url_parser.parse_url
    httptools.parser.errors.HttpParserInvalidURLError: invalid url b'sip:nm'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "connection_task", line 15, in connection_task
        from asyncio import CancelledError
      File "/opt/conda/lib/python3.9/site-packages/sanic/http/http1.py", line 149, in http1
        await self.error_response(e)
      File "/opt/conda/lib/python3.9/site-packages/sanic/http/http1.py", line 425, in error_response
        self.create_empty_request()
      File "/opt/conda/lib/python3.9/site-packages/sanic/http/http1.py", line 437, in create_empty_request
        self.request = self.protocol.request_class(
      File "/opt/conda/lib/python3.9/site-packages/sanic/request.py", line 147, in __init__
        raise BadURL(f"Bad URL: {url_bytes.decode()}")
    sanic.exceptions.BadURL: Bad URL: sip:nm

**Comment by ahopkins** [comment]
This comes from here: #2415

As the message states, you are receiving requests with an invalid URL so Sanic cannot process it. You should try and trackdown where this request came from.
