### ISSUE TITLE
Run normally under macos, run error report on Ubuntu.

### ISSUE THREAD

**Issue by jiayouzl** [sanic-org/sanic#2547]
```
@app.get('/admin/card_info/')
@app.ext.template('card_info.html')
async def card_info(request: Request):
    page = 1 if (request.args.get('page') is None) else int(request.args.get('page'))
    card_info = verify.get_card(page, 20)
    home_page = 1
    previous_page = 1 if (page - 1 == 0) else page - 1
    next_page = card_info['all_page'] if (page + 1 > card_info['all_page']) else page + 1
    end_page = card_info['all_page']
    return {'title': '充值卡管理', 'card_data': card_info['data'], 'page': [home_page, previous_page, next_page, end_page]}
```

Run normally under macos, run error report on Ubuntu.
```
(venv) ubuntu@VM-4-7-ubuntu:/www/wwwroot/test_python$ python3 app.py 
Traceback (most recent call last):
  File "/www/wwwroot/test_python/app.py", line 123, in <module>
    @app.ext.template('card_info.html')
  File "/www/wwwroot/test_python/venv/lib/python3.9/site-packages/sanic_ext/bootstrap.py", line 154, in template
    return self.templating.template(template_name, **kwargs)
AttributeError: 'Extend' object has no attribute 'templating'
```

`AttributeError: 'Extend' object has no attribute 'templating'`

**Comment by sermuns** [comment]
How was this solved?
