### ISSUE TITLE
Autoreload does not work with setuptools in 22.9.0

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [sanic-org/sanic#2573]
**Describe the bug**

Starting with 22.9.0, autoreload crashes when installing a package in development mode using setuptools. This used to work in 22.6.2.

**Code snippet**
`server.py`
```
from sanic import Sanic
from sanic.response import text

app = Sanic("MyHelloWorldApp")

@app.get("/")
async def hello_world(request):
    return text("Hello, world.")

def main():
    app.run(auto_reload=True)
```

`setup.py`
```
import setuptools

setuptools.setup(
    name='test',
    packages=[],
    python_requires='>=3.7',
    install_requires=['sanic'],
    entry_points={'console_scripts': [
        'test-server=server:main',
    ]},
    )
```

Run the following:
```
pip install -e .
test-server
```

The following error occurs:
```
Traceback (most recent call last):
  File "<..>/venv/lib/python3.10/site-packages/sanic/app.py", line 1450, in get_app
    return cls._app_registry[name]
KeyError: 'MyHelloWorldApp'
```

<details><summary>Full output</summary>
<p>

```
$ test-server
[2022-10-16 07:39:07 +0200] [4304] [INFO] 
  ┌──────────────────────────────────────────────────────────────────────────────────┐
  │                                  Sanic v22.9.0                                   │
  │                        Goin' Fast @ http://127.0.0.1:8000                        │
  ├───────────────────────┬──────────────────────────────────────────────────────────┤
  │                       │        mode: production, single worker                   │
  │     ▄███ █████ ██     │      server: sanic, HTTP/1.1                             │
  │    ██                 │      python: 3.10.7                                      │
  │     ▀███████ ███▄     │    platform: Linux-5.19.13-arch1-1-x86_64-with-glibc2.36 │
  │                 ██    │ auto-reload: enabled                                     │
  │    ████ ████████▀     │    packages: sanic-routing==22.8.0                       │
  │                       │                                                          │
  │ Build Fast. Run Fast. │                                                          │
  └───────────────────────┴──────────────────────────────────────────────────────────┘

[2022-10-16 07:39:07 +0200] [4304] [WARNING] Sanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.
Process Sanic-Reloader-0:
Traceback (most recent call last):
  File "<..>/venv/lib/python3.10/site-packages/sanic/app.py", line 1450, in get_app
    return cls._app_registry[name]
KeyError: 'MyHelloWorldApp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "<..>/venv/lib/python3.10/site-packages/sanic/worker/reloader.py", line 33, in __call__
    app = self.app_loader.load()
  File "<..>/venv/lib/python3.10/site-packages/sanic/worker/loader.py", line 60, in load
    return self.factory()
  File "<..>/venv/lib/python3.10/site-packages/sanic/app.py", line 1456, in get_app
    raise SanicException(f'Sanic app name "{name}" not found.')
sanic.exceptions.SanicException: Sanic app name "MyHelloWorldApp" not found.
Process Sanic-Server-0-0:
Traceback (most recent call last):
  File "<..>/venv/lib/python3.10/site-packages/sanic/app.py", line 1450, in get_app
    return cls._app_registry[name]
KeyError: 'MyHelloWorldApp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "<..>/venv/lib/python3.10/site-packages/sanic/worker/serve.py", line 51, in worker_serve
    app = app_loader.load()
  File "<..>/venv/lib/python3.10/site-packages/sanic/worker/loader.py", line 60, in load
    return self.factory()
  File "<..>/venv/lib/python3.10/site-packages/sanic/app.py", line 1456, in get_app
    raise SanicException(f'Sanic app name "{name}" not found.')
sanic.exceptions.SanicException: Sanic app name "MyHelloWorldApp" not found.
[2022-10-16 07:39:12 +0200] [4304] [ERROR] Not all workers are ack. Shutting down.
[2022-10-16 07:39:12 +0200] [4304] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "<..>/venv/lib/python3.10/site-packages/sanic/mixins/startup.py", line 851, in serve
    manager.run()
  File "<..>/venv/lib/python3.10/site-packages/sanic/worker/manager.py", line 63, in run
    self.monitor()
  File "<..>/venv/lib/python3.10/site-packages/sanic/worker/manager.py", line 99, in monitor
    self.wait_for_ack()
  File "<..>/venv/lib/python3.10/site-packages/sanic/worker/manager.py", line 139, in wait_for_ack
    sys.exit(1)
SystemExit: 1
[2022-10-16 07:39:12 +0200] [4304] [INFO] Server Stopped
```

</p>
</details>

**Expected behavior**

A working server with autoreload

**Environment (please complete the following information):**

 - OS: Linux
 - Sanic Version: 22.9.0

**Comment by ahopkins** [comment]
This is not a bug.

You should make sure to familiarize yourself with [Running Sanic](https://sanic.dev/en/guide/deployment/running.html). I just added some docs on [using the `AppLoader`](https://sanic.dev/en/guide/deployment/app-loader.html), which is likely what you will need here.

Since you are running Sanic in a non-standard way, we just need to add some additional low-level pluming so the worker processes know how to find your application.

I tested this with your `setup.py` and it should work as expected.

```python
from sanic import Sanic
from sanic.response import text
from sanic.worker.loader import AppLoader

app = Sanic("MyHelloWorldApp")


@app.get("/")
async def hello_world(request):
    return text("Hello, world.")


def main():
    loader = AppLoader("server:app")
    app = loader.load()
    app.prepare(port=9999, dev=True)
    Sanic.serve(primary=app, app_loader=loader)

```
