### ISSUE TITLE
Cannot run synchronous server since 22.9.0

### ISSUE THREAD

**Issue by harpener** [sanic-org/sanic#2574]
Hi guys,

**Describe the bug**

Since upgrading Sanic to version 22.9.0, my every attempt to run the server ends in some exception.

If I try to run the application without legacy mode, I get

```python
Traceback (most recent call last):
  File "path-to-myapp\lib\site-packages\sanic\app.py", line 1450, in get_app
    return cls._app_registry[name]
KeyError: 'myapp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "path-to-myapp\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "path-to-myapp\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "path-to-myapp\lib\site-packages\sanic\worker\serve.py", line 51, in worker_serve
    app = app_loader.load()
  File "path-to-myapp\lib\site-packages\sanic\worker\loader.py", line 60, in load
    return self.factory()
  File "path-to-myapp\lib\site-packages\sanic\app.py", line 1456, in get_app
    raise SanicException(f'Sanic app name "{name}" not found.')
```

If I try to run the application with legacy mode, I get

```python
Traceback (most recent call last):
  File "path-to-myapp\lib\site-packages\sanic\mixins\startup.py", line 991, in serve_legacy
    serve_single(primary_server_info.settings)
  File "path-to-myapp\lib\site-packages\sanic\server\runners.py", line 331, in serve_single
    serve(**server_settings)
  File "path-to-myapp\lib\site-packages\sanic\server\runners.py", line 106, in serve
    return _serve_http_1(
  File "path-to-myapp\lib\site-packages\sanic\server\runners.py", line 205, in _serve_http_1
    sock = sock.share(pid)
AttributeError: 'NoneType' object has no attribute 'share'
```

**Code snippet**

```python
#  server.py
from sanic import response, Sanic

app = Sanic("myapp")


@app.get("/health")
async def on_get_health(request):
    return response.text("", 200)
```

```python
#  __main__.py
from server import app


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=3456)
```

**Expected behavior**

The server should start and serve the requests.

**Environment**

```
Sanic v22.9.0

mode: production, single worker
server: sanic, HTTP/1.1
python: 3.10.7
platform: Windows-10-10.0.22000-SP0
packages: sanic-routing==22.8.0
```

Do you have any idea what I'm doing wrong? Thanks for help.

**Comment by ahopkins** [comment]
This does not appear to be a bug. Using your files, when I run...

```
python .
```

...everything seems okay.

Regardless, you may need to look into the the docs on using the `AppLoader`: https://sanic.dev/en/guide/deployment/app-loader.html

**Comment by harpener** [comment]
I just tried it with just my files and only `sanic` installed and it really does not work at all. There are also some `PermissionError` exceptions raised during the shutdown if it is anyhow relevant.

But the solution with AppLoader seems to work for me, thanks for the suggestion.

**Comment by ahopkins** [comment]
Since you app is a global scope in a package, you could do something like this that uses a similar API as the CLI when referencing the module/application.

```python
loader = AppLoader("path.to.server:app")
```
