### ISSUE TITLE
Sanic v22.9 server could not be start with `add_route()`

### ISSUE THREAD

**Issue by Xnollis** [sanic-org/sanic#2583]
**Describe the bug**
The "Hello world" demo failed to start and stopped automatically because of below exceptions:
===========start======================
Traceback (most recent call last):
  File "C:\prog\.venv\lib\site-packages\sanic\app.py", line 1450, in get_app
    return cls._app_registry[name]
KeyError: 'MyHelloWorldApp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tyrant\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\tyrant\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\prog\.venv\lib\site-packages\sanic\worker\serve.py", line 51, in worker_serve
    app = app_loader.load()
  File "C:\prog\.venv\lib\site-packages\sanic\worker\loader.py", line 60, in load
    return self.factory()
  File "C:\prog\.venv\lib\site-packages\sanic\app.py", line 1456, in get_app
    raise SanicException(f'Sanic app name "{name}" not found.')
sanic.exceptions.SanicException: Sanic app name "MyHelloWorldApp" not found.
[11504] [ERROR] Not all workers are ack. Shutting down.
[11504] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "C:\prog\.venv\lib\site-packages\sanic\mixins\startup.py", line 851, in serve
    manager.run()
  File "C:\prog\.venv\lib\site-packages\sanic\worker\manager.py", line 63, in run
    self.monitor()
  File "C:\prog\.venv\lib\site-packages\sanic\worker\manager.py", line 99, in monitor
    self.wait_for_ack()
  File "C:\prog\.venv\lib\site-packages\sanic\worker\manager.py", line 138, in wait_for_ack
    self.kill()
  File "C:\prog\.venv\lib\site-packages\sanic\worker\manager.py", line 159, in kill
    os.kill(process.pid, SIGKILL)
PermissionError: [WinError 5] Access denied
[2022-10-21 20:22:13 +0800] [11504] [INFO] Server Stopped
Traceback (most recent call last):
  File "C:\Users\tyrant\Documents\gy-sso\test\main2.py", line 12, in <module>
    app.run()
  File "C:\prog\.venv\lib\site-packages\sanic\mixins\startup.py", line 206, in run
    serve(primary=self)  # type: ignore
  File "C:\prog\.venv\lib\site-packages\sanic\mixins\startup.py", line 851, in serve
    manager.run()
  File "C:\prog\.venv\lib\site-packages\sanic\worker\manager.py", line 63, in run
    self.monitor()
  File "C:\prog\.venv\lib\site-packages\sanic\worker\manager.py", line 99, in monitor
    self.wait_for_ack()
  File "C:\prog\.venv\lib\site-packages\sanic\worker\manager.py", line 138, in wait_for_ack
    self.kill()
  File "C:\prog\.venv\lib\site-packages\sanic\worker\manager.py", line 159, in kill
    os.kill(process.pid, SIGKILL)
PermissionError: [WinError 5] Access denied
============end=========================

**This issue could be reshown by following steps:**
`python3 -m venv myvenv`

`source ./myvenv/bin/activate`

`pip3 install sanic`

`vim hello_world.py`

Content of hello_world.py(or download here [hello_world.txt](https://github.com/sanic-org/sanic/files/9839299/hello_world.txt) ):
========hello_world.py start================
from sanic import Sanic
from sanic.response import text

async def hello_world(request):
    return text("Hello, world.")

if __name__ == '__main__':
    app = Sanic("MyHelloWorldApp")`
    app.add_route(hello_world, '/')
    app.run()
========hello_world.py end================

**Then start this py file:**
`python3 hello_world.py`

**Expected behavior**
Sanic server should be started correctly.

**Environment (please complete the following information):**

 - OS: Windows10 x64 and macOS 11.5 x64 (Intel)
 - Sanic Version:  v22.9.0 
 - Python Version: 3.10.7

**Comment by Tronic** [comment]
`app` needs to be defined outside of `in __name__ = "__main__":`

Closing as there are plenty of duplicates of this issue.

**Comment by ahopkins** [comment]
This is in the docs and latest release notes.

**Comment by Xnollis** [comment]
> 

after move `app=Sanic("MyHelloWorldApp")` outside of `if __name__ == "__main__":`, like this:
....
app=Sanic("MyHelloWorldApp")
if __name__ == "__main__":
   ...
   ...
....

**the problem still remains.** 
But exception information is different:
=========start====================
Process Sanic-Server-0-0:
Traceback (most recent call last):
  File "C:\Users\tyrant\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap    
    self.run()
  File "C:\Users\tyrant\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\prog\.venv\lib\site-packages\sanic\worker\serve.py", line 106, in worker_serve     
    return _serve_http_1(
  File "C:\prog\.venv\lib\site-packages\sanic\server\runners.py", line 230, in _serve_http_1  
    loop.run_until_complete(app._startup())
  File "C:\Users\tyrant\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\prog\.venv\lib\site-packages\sanic\app.py", line 1503, in _startup
    self.finalize()
  File "C:\prog\.venv\lib\site-packages\sanic\app.py", line 1477, in finalize
    raise e
  File "C:\prog\.venv\lib\site-packages\sanic\app.py", line 1474, in finalize
    self.router.finalize()
  File "C:\prog\.venv\lib\site-packages\sanic\router.py", line 190, in finalize
    super().finalize(*args, **kwargs)
  File "C:\prog\.venv\lib\site-packages\sanic_routing\router.py", line 319, in finalize       
    raise FinalizationError("Cannot finalize with no routes defined.")
sanic_routing.exceptions.FinalizationError: Cannot finalize with no routes defined.
sys:1: RuntimeWarning: coroutine 'BaseEventLoop.create_server' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback       
[8972] [ERROR] Not all workers are ack. Shutting down.
[8972] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "C:\prog\.venv\lib\site-packages\sanic\mixins\startup.py", line 851, in serve 
    manager.run()
  File "C:\prog\.venv\lib\site-packages\sanic\worker\manager.py", line 63, in run    
    self.monitor()
  File "C:\prog\.venv\lib\site-packages\sanic\worker\manager.py", line 99, in monitor
    self.wait_for_ack()
  File "C:\prog\.venv\lib\site-packages\sanic\worker\manager.py", line 138, in wait_for_ack
    self.kill()
  File "C:\prog\.venv\lib\site-packages\sanic\worker\manager.py", line 159, in kill
    os.kill(process.pid, SIGKILL)
PermissionError: [WinError 5] Access denied
[8972] [INFO] Server Stopped
Traceback (most recent call last):
  File "C:\prog\main2.py", line 15, in <module>
    app.run(host="127.0.0.1", port=8000, access_log=False)
  File "C:\prog\.venv\lib\site-packages\sanic\mixins\startup.py", line 206, in run
    serve(primary=self)  # type: ignore
  File "C:\prog\.venv\lib\site-packages\sanic\mixins\startup.py", line 851, in serve
    manager.run()
  File "C:\prog\.venv\lib\site-packages\sanic\worker\manager.py", line 63, in run
    self.monitor()
  File "C:\prog\.venv\lib\site-packages\sanic\worker\manager.py", line 99, in monitor
    self.wait_for_ack()
  File "C:\prog\.venv\lib\site-packages\sanic\worker\manager.py", line 138, in wait_for_ack
    self.kill()
  File "C:\prog\.venv\lib\site-packages\sanic\worker\manager.py", line 159, in kill
    os.kill(process.pid, SIGKILL)
PermissionError: [WinError 5] Access denied

**Comment by Xnollis** [comment]
> This is in the docs and latest release notes. With the change for https://github.com/sanic-org/sanic/pull/2582, the existing error message that catches and prompts the used to use this block on Linux should start appearing on windows. Patch coming next week.

OK, thans, this issue now only occurred on windows.
