### ISSUE TITLE
Unable to handle global scope on Windows

### ISSUE THREAD

**Issue by SaidBySolo** [sanic-org/sanic#2584]
**Describe the bug**

On Windows I get a runtime error telling me to call freeze_support, when run code snippet

```py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Python310\lib\runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\Juheon\Documents\playground\server.py", line 5, in <module>
    app.run(workers=4)
  File "C:\Users\Juheon\Documents\playground\.venv\lib\site-packages\sanic\mixins\startup.py", line 208, in run
    serve(primary=self)  # type: ignore
  File "C:\Users\Juheon\Documents\playground\.venv\lib\site-packages\sanic\mixins\startup.py", line 727, in serve
    sync_manager = Manager()
  File "C:\Python310\lib\multiprocessing\context.py", line 57, in Manager
    m.start()
  File "C:\Python310\lib\multiprocessing\managers.py", line 562, in start
    self._process.start()
  File "C:\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Python310\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Python310\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Python310\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Python310\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

```

**Code snippet**
```py
from sanic import Sanic

app = Sanic("server")

app.run(worker=4)
```

**Expected behavior**

should be handled like this:
https://sanic.dev/en/guide/release-notes/v22.9.html#potential-upgrade-issues

**Environment (please complete the following information):**

 - OS: Windows 10
 - Sanic Version: 22.9

**Additional context**

**Comment by ahopkins** [comment]
It is the exact same message, except coming from Python instead. I don't see anything we need to do on this.
