### ISSUE TITLE
Datetime issue with Python 3.11 (with fix)

### ISSUE THREAD

**Issue by stricaud** [sanic-org/sanic#2694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am getting various exceptions like this:
```
[2023-02-24 22:41:25 +0100] [512643] [ERROR] Exception in static request handler: path=static, relative_url=fonts/general.woff2
Traceback (most recent call last):
  File "/home/sebastien/.local/lib/python3.11/site-packages/sanic/mixins/routes.py", line 848, in _static_request_handler
    response = await validate_file(request.headers, modified_since)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sebastien/.local/lib/python3.11/site-packages/sanic/response/convenience.py", line 151, in validate_file
    if last_modified <= if_modified_since:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't compare offset-naive and offset-aware datetimes
```
Which is fixed by ensuring last_modified and if_modified_since are converted to proper timestamps():
```
if last_modified.timestamp() <= if_modified_since.timestamp():
```

### How do you run Sanic?

Sanic CLI

### Operating System

Linux Debian

### Sanic Version

Sanic 22.12.0; Routing 22.8.0

**Comment by ahopkins** [comment]
Excellent. Can you open a PR with this fix and a unit test?

**Comment by stricaud** [comment]
absolutely
