### ISSUE TITLE
Cannot use pdb with Sanic

### ISSUE THREAD

**Issue by j-laurie** [sanic-org/sanic#2714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using pdb I cannot break into the debugger. When my app reaches `import pdb; pdb.set_trace()` the debugger immediately raises bdb.BdbQuit. See below the exception traceback/output:
```
> /Users/<my_name>/scripts/sanic_pdb_test/app.py(9)hello_world()
-> return text("Hello, world.")
(Pdb) 
[2023-03-17 16:23:20 +0000] [80080] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:8000/'
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/sanic/app.py", line 968, in handle_request
    response = await response
  File "/Users/<my_name>/scripts/sanic_pdb_test/app.py", line 9, in hello_world
    return text("Hello, world.")
  File "/Users/<my_name>/scripts/sanic_pdb_test/app.py", line 9, in hello_world
    return text("Hello, world.")
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
``` 

### Code snippet

The error was obtained by running `sanic app.app --debug`

The app.py file is:
```
from sanic import Sanic
from sanic.response import text

app = Sanic("MyHelloWorldApp")

@app.get("/")
async def hello_world(request):
    import pdb; pdb.set_trace()
    return text("Hello, world.")
```

### Expected Behavior

The app breaks into the debugger. I can use all of the normal pdb commands.

### How do you run Sanic?

Sanic CLI

### Operating System

macOS 13.2.1 M1 Pro

### Sanic Version

v22.12.0

### Additional context

This bug seems to have been introduced in 22.9.0

**Comment by ahopkins** [comment]
I am going to guess this is because of the runtime optimizations. You can opt out using this:

```py
app.config.TOUCHUP = False
```

If this does not solve your problem, LMK.

**Comment by j-laurie** [comment]
Hi, I've added that line just after `app = Sanic("MyHelloWorldApp")` but that hasn't fixed the issue.

**Comment by Tronic** [comment]
Try running with `--single-process --debug` as that might help your debugger follow what is happening. Note that you cannot use auto-reloader, `--dev` or `--fast` in single process mode.
