### ISSUE TITLE
sanic.exceptions.BadURL: Bad URL: sip:nm

### ISSUE THREAD

**Issue by vgoklani** [sanic-org/sanic#2735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

For some reason I occasionally see these types of messages in my logs:

```
[2023-03-29 00:42:04 -0400] - (sanic.access)[INFO][UNKNOWN]: NONE http:///*  500 139
[2023-03-29 00:42:09 -0400] - (sanic.access)[INFO][UNKNOWN]: NONE http:///*  500 139
[2023-03-29 00:42:14 -0400] - (sanic.access)[INFO][UNKNOWN]: NONE http:///*  500 139
[2023-03-29 00:42:19 -0400] - (sanic.access)[INFO][UNKNOWN]: NONE http:///*  500 139
[2023-03-29 00:42:24 -0400] - (sanic.access)[INFO][UNKNOWN]: NONE http:///*  500 139
[2023-03-29 00:42:29 -0400] - (sanic.access)[INFO][UNKNOWN]: NONE http:///*  500 139
[2023-03-29 00:42:35 -0400] - (sanic.access)[INFO][UNKNOWN]: NONE http:///*  500 139
[2023-03-29 00:42:40 -0400] - (sanic.access)[INFO][UNKNOWN]: NONE http:///*  500 139
[2023-03-29 00:42:45 -0400] - (sanic.access)[INFO][UNKNOWN]: NONE http:///*  500 139
[2023-03-29 00:42:50 -0400] - (sanic.access)[INFO][UNKNOWN]: NONE http:///*  500 139
[2023-03-29 00:42:55 -0400] - (sanic.access)[INFO][UNKNOWN]: NONE http:///*  500 139
```

which lead to subsequent crashes:

```bash
[2023-03-29 00:42:09 -0400] [2306] [ERROR] protocol.connection_task uncaught
Traceback (most recent call last):
  File "http1_request_header", line 41, in http1_request_header
    :raises RuntimeError:
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/sanic/http/http1.py", line 123, in http1
    await self.http1_request_header()
  File "http1_request_header", line 57, in http1_request_header
    )
sanic.exceptions.BadRequest: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/sanic/request.py", line 152, in __init__
    self._parsed_url = parse_url(url_bytes)
  File "httptools/parser/url_parser.pyx", line 105, in httptools.parser.url_parser.parse_url
httptools.parser.errors.HttpParserInvalidURLError: invalid url b'sip:nm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "connection_task", line 15, in connection_task
    from asyncio import CancelledError
  File "/opt/conda/lib/python3.10/site-packages/sanic/http/http1.py", line 153, in http1
    await self.error_response(e)
  File "/opt/conda/lib/python3.10/site-packages/sanic/http/http1.py", line 429, in error_response
    self.create_empty_request()
  File "/opt/conda/lib/python3.10/site-packages/sanic/http/http1.py", line 447, in create_empty_request
    self.request = self.protocol.request_class(
  File "/opt/conda/lib/python3.10/site-packages/sanic/request.py", line 154, in __init__
    raise BadURL(f"Bad URL: {url_bytes.decode()}")
sanic.exceptions.BadURL: Bad URL: sip:nm
```

What's the best way of handling this; sanic shouldn't crash when it sees a URL that's presumably masked? 

This is in fact the same issue as this, which I never resolved before:

https://github.com/sanic-org/sanic/issues/2528

### How do you run Sanic?

As a script (`app.run` or `Sanic.serve`)

### Operating System

LINUX

### Sanic Version

latest

**Comment by dinosaurtirex** [comment]
Hello! I had similar issue. It occurs when someone trying to do invalid requests to backend server, from requests library or from npm frontend server. I don't know it is your case or not, but may be it helps you to resolve this.

**Comment by prryplatypus** [comment]
Is the server actually crashing or is it just leaving an ugly-looking traceback?

**Comment by sjsadowski** [comment]
This is a something on the internet searching for a SIP endpoint to do a registration. 

It should be getting handled with a 404 because the route doesn't exist. Not sure what the right path forward for this is, but that's the cause.

**Comment by Tronic** [comment]
Which client sends such requests? This is not normal by any means but the HTTP spec allows including full URL rather than path in request, and for http Sanic can parse that (but I've never seen a client to it). But Sanic is a http server, not a sip server, and thus cannot parse sip URLs, and technically cannot even respond to other protocol URLs (but I presume it could do 400 Bad Request HTTP response and then disconnect the client, as it does for other invalid requests).

**Comment by Tronic** [comment]
Two points of action for Sanic. It currently hits this BadURL error in Request constructor, when `httptools.parse_url` fails. The first point, this should be silent and instead actually delived that response to client and log it with 4xx code (need to check why this is not working).

Secondly, make sure that 422 error is given if appropriate, even if the parsing is successful i.e. a client send http URL with unknown authority (host not known to server), or use the host from URL instead of host header etc. But I would really like to see a real client and use case where this is an issue, to better think how it ought to be handled (e.g. Sanic accepting any authority, but should it give 400 error if there is a mismatch between that and the host header, really hairy territory on how to handle such cases correctly).

**Comment by prryplatypus** [comment]
Pretty sure it's some tools like `nmap`.

**Comment by Tronic** [comment]
On point 1 above, I see this is properly handled in http1 main protocol, but then it crashes in making the error response in `create_empty_request`, that for better logs/messages still attempts to use that URL. Thus for error handling we need to simply clear the URL at some point for various errors to pass. And ideally so that we don't need much code repetition between http1, http3 and asgi, which already duplicate plenty of the error handling code (i.e. might need a bit of refactoring for the whole process). Not gonna be working on a fix myself, but that should give a good starting point if anyone wants to have a go at it.

The related errors that probably also fail in a similar fashion are various BadRequest errors risen e.g. for non-ASCII characters in URLs, so it isn't enough to simply clear the URL in request constructor when parse_url fails.

**Comment by Tronic** [comment]
A quick patch fixes the handling, giving clean 400 error for `sip:nm`
```diff
diff --git a/sanic/http/http1.py b/sanic/http/http1.py
index bb317a9..42e08fe 100644
--- a/sanic/http/http1.py
+++ b/sanic/http/http1.py
@@ -450,18 +450,9 @@ class Http(Stream, metaclass=TouchUpMeta):
         bogus response for error handling use.
         """

-        # Reformat any URL already received with \xHH escapes for better logs
-        url_bytes = (
-            self.url.encode(errors="surrogateescape")
-            .decode("ASCII", errors="backslashreplace")
-            .encode("ASCII")
-            if self.url
-            else b"*"
-        )
-
         # FIXME: Avoid this by refactoring error handling and response code
         self.request = self.protocol.request_class(
-            url_bytes=url_bytes,
+            url_bytes=b"*",
             headers=Header({}),
             version="1.1",
             method="NONE",
```

**Comment by Tronic** [comment]
The invalid URL is included in the exception message itself, so the client will see it, although in server log `http:///*` appears instead of what was actually attempted. If Request constructor passes, this patched function won't be called anyway and you get your normal error log and error pages incl. request url and headers.
