### ISSUE TITLE
Support for Python 3.12

### ISSUE THREAD

**Issue by robd003** [sanic-org/sanic#2836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Currently unable to use Sanic with Python 3.12

### Describe the solution you'd like

[uvloop 0.18.0 was just released](https://github.com/MagicStack/uvloop/releases/tag/v0.18.0) and supports Python 3.12

It'd be great to get support for Python 3.12 on the next release of Sanic along with the 2022.12 LTS release

**Comment by Tronic** [comment]
Making this the tracking issue for Python 3.12 compatibility. Please post any incompatibilities found here. We probably need to update some dependencies, and add 3.12 testing to our CI. Rarely have any Python updates (other than asyncio loop argument removal) prompted for changes in Sanic itself.

**Comment by iAndriy** [comment]
@ahopkins Is this feature something what is okay to pick up into progress by someone whom isn't part of the core maintainers group ?

**Comment by Tronic** [comment]
@iAndriy Feel free to hack it, PRs from anyone are welcome here! And core developers are quite overloaded already =)

**Comment by ahopkins** [comment]
A good start would be to just add to the CI, open a PR, mark it as draft and list out all the errors you encountered.

**Comment by iAndriy** [comment]
> A good start would be to just add to the CI, open a PR, mark it as draft and list out all the errors you encountered.
> 
> First and foremost add it to tox.ini and run the tests.
> 
> ```
> tox -e py312
> ```

@ahopkins thanks for suggestion

**Comment by iAndriy** [comment]
Sanic code which relies on "websockets.server.ServerConnection"  fails with exception, sample of it below
```
[2023-12-06 18:38:53 -0500] [86323] [INFO] Server Stopped
[2023-12-06 18:38:53 -0500] [86323] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:58513/tempest'
Traceback (most recent call last):
  File "handle_request", line 100, in handle_request
    if TYPE_CHECKING:
                      
  File "/Users/andriy/Projects/sanic/tests/test_exceptions.py", line 251, in tempest
    raise TeaError
tests.test_exceptions.test_custom_exception_default_message.<locals>.TeaError: Tempest in a teapot
Fatal Python error: Segmentation fault

Thread 0x0000700011d4a000 (most recent call first):
  File "/Users/andriy/.pyenv/versions/3.12.0/lib/python3.12/threading.py", line 338 in wait
  File "/Users/andriy/.pyenv/versions/3.12.0/lib/python3.12/threading.py", line 634 in wait
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 150 in _on_run
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 219 in run
  File "/Users/andriy/.pyenv/versions/3.12.0/lib/python3.12/threading.py", line 1052 in _bootstrap_inner
  File "/Users/andriy/.pyenv/versions/3.12.0/lib/python3.12/threading.py", line 1009 in _bootstrap

Thread 0x0000700010d47000 (most recent call first):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 293 in _on_run
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 219 in run
  File "/Users/andriy/.pyenv/versions/3.12.0/lib/python3.12/threading.py", line 1052 in _bootstrap_inner
  File "/Users/andriy/.pyenv/versions/3.12.0/lib/python3.12/threading.py", line 1009 in _bootstrap

Thread 0x000070000fd44000 (most recent call first):
  File "/Users/andriy/.pyenv/versions/3.12.0/lib/python3.12/threading.py", line 338 in wait
  File "/Users/andriy/.pyenv/versions/3.12.0/lib/python3.12/queue.py", line 180 in get
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 368 in _on_run
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 219 in run
  File "/Users/andriy/.pyenv/versions/3.12.0/lib/python3.12/threading.py", line 1052 in _bootstrap_inner
  File "/Users/andriy/.pyenv/versions/3.12.0/lib/python3.12/threading.py", line 1009 in _bootstrap

Current thread 0x00007ff8443ae700 (most recent call first):
  File "/Users/andriy/Projects/sanic/sanic/compat.py", line 133 in get_all
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/websockets/server.py", line 202 in process_request
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/websockets/server.py", line 111 in accept
  File "/Users/andriy/Projects/sanic/sanic/server/protocols/websocket_protocol.py", line 120 in websocket_handshake
  File "/Users/andriy/Projects/sanic/sanic/app.py", line 1421 in _websocket_handler
  File "handle_request", line 102 in handle_request
  File "/Users/andriy/Projects/sanic/sanic/http/http1.py", line 119 in http1
  File "connection_task", line 15 in connection_task
  File "/Users/andriy/Projects/sanic/sanic/server/runners.py", line 300 in _serve_http_1
  File "/Users/andriy/Projects/sanic/sanic/worker/serve.py", line 117 in worker_serve
  File "/Users/andriy/Projects/sanic/sanic/mixins/startup.py", line 1244 in serve_single
  File "/Users/andriy/Projects/sanic/sanic/mixins/startup.py", line 288 in run
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/sanic_testing/testing.py", line 238 in _sanic_endpoint_test
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/sanic_testing/testing.py", line 318 in websocket
  File "/Users/andriy/Projects/sanic/tests/test_exceptions.py", line 266 in test_exception_in_ws_logged
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/_pytest/python.py", line 192 in pytest_pyfunc_call
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 77 in _multicall
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/pluggy/_manager.py", line 115 in _hookexec
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/pluggy/_hooks.py", line 493 in __call__
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/_pytest/python.py", line 1761 in runtest
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/_pytest/runner.py", line 166 in pytest_runtest_call
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 77 in _multicall
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/pluggy/_manager.py", line 115 in _hookexec
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/pluggy/_hooks.py", line 493 in __call__
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/_pytest/runner.py", line 259 in <lambda>
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/_pytest/runner.py", line 338 in from_call
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/_pytest/runner.py", line 258 in call_runtest_hook
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/_pytest/runner.py", line 219 in call_and_report
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/_pytest/runner.py", line 130 in runtestprotocol
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/_pytest/runner.py", line 111 in pytest_runtest_protocol
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 77 in _multicall
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/pluggy/_manager.py", line 115 in _hookexec
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/pluggy/_hooks.py", line 493 in __call__
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/_pytest/main.py", line 347 in pytest_runtestloop
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 77 in _multicall
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/pluggy/_manager.py", line 115 in _hookexec
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/pluggy/_hooks.py", line 493 in __call__
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/_pytest/main.py", line 322 in _main
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/_pytest/main.py", line 268 in wrap_session
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/_pytest/main.py", line 315 in pytest_cmdline_main
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 77 in _multicall
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/pluggy/_manager.py", line 115 in _hookexec
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/pluggy/_hooks.py", line 493 in __call__
  File "/Users/andriy/Projects/sanic/venv/lib/python3.12/site-packages/_pytest/config/__init__.py", line 164 in main
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pycharm/_jb_pytest_runner.py", line 60 in <module>
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18 in execfile
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1500 in _exec
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1493 in run
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2181 in main
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2199 in <module>

Extension modules: markupsafe._speedups, _pydevd_bundle.pydevd_cython_darwin_312_64, _pydevd_bundle.pydevd_cython, multidict._multidict, uvloop.loop, _cffi_backend, httptools.parser.parser, httptools.parser.url_parser, ujson, websockets.speedups (total: 10)
```

**Comment by iAndriy** [comment]
Some of upstreams libraries used by sanic doesn't support Python 3.12:
- [CIMultiDict](https://github.com/aio-libs/multidict/issues/887)
- [wbsockets](https://github.com/python-websockets/websockets/issues/1417)

The failure of test suite for py312 in https://github.com/sanic-org/sanic/pull/2870 is related to errors caused from by CIMultiDict

**Comment by iAndriy** [comment]
@ahopkins @Tronic Looks like we need to wait a bit, so upstream libraries would catch up with latest python. 
Related MR: https://github.com/sanic-org/sanic/pull/2870, see test execution for python 3.12 + comment above for more details. 
How do you usually overcome such use cases ?

**Comment by aaugustin** [comment]
websockets works on Python 3.12 without any code changes. There's even Python 3.12 wheels for websockets 12.0 [on PyPI](https://pypi.org/project/websockets/#files).

Only the Python 3.12 trove classifier is missing on PyPI. I will add it; however, I believe this metadata is indicative and doesn't affect whether pip & friends will accept to install a library. This shouldn't prevent you from moving forwards.

If I'm missing something here and the missing classifier is actually a blocker, then I can do a quick 12.0.1 release just to fix that!

**Comment by ahopkins** [comment]
Thanks @aaugustin! @iAndriy can you take a look? I don't think the lack of classifier would hold us back.

**Comment by iAndriy** [comment]
@ahopkins I've updated MR, issues seems to be in the CIMultiDict call flow. For python3.12 the following call results in Segmentation Fault ( see screenshot), nonetheless it works if no kwargs used.
<img width="806" alt="Screenshot 2023-12-17 at 17 12 45" src="https://github.com/sanic-org/sanic/assets/3365831/7c9e2e64-daba-4339-a04c-56e88d7ed2fa">

**Comment by JoeriHermans** [comment]
Experiencing the same issue as @iAndriy Through `websocket` endpoints though.

**Comment by iAndriy** [comment]
Relevant issue within multidict: https://github.com/aio-libs/multidict/issues/898
+ no error present when kwargs aren't used.

**Comment by wieczorek1990** [comment]
Bump.
