### ISSUE TITLE
RuntimeError: Event loop stopped before Future completed.

### ISSUE THREAD

**Issue by KlimchevKonstantin** [sanic-org/sanic#2948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Python 3.12.3
sanic-23.12.1

very often (not 100%) after restarting worker, for example: 
@apt.get("/restart")

I get this output after Ctrl-C:

```
(.venv) koka@BEELINK-GTR6:~/work/python/saymon/netscan-sanic$ /home/koka/work/python/saymon/netscan-sanic/.venv/bin/python /home/koka/work/python/saymon/netscan-sanic/run.py
[2024-05-13 11:56:27 +0300] [37003] [WARNING] Sanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.
[2024-05-13 11:56:27 +0300] [37013] [INFO] I'm worker
[2024-05-13 11:56:27 +0300] [37012] [INFO] Sanic Extensions:
[2024-05-13 11:56:27 +0300] [37012] [INFO]   > injection [0 dependencies; 0 constants]
[2024-05-13 11:56:27 +0300] [37012] [INFO]   > openapi [http://0.0.0.0:8000/docs]
[2024-05-13 11:56:27 +0300] [37012] [INFO]   > http 
/home/koka/work/python/saymon/netscan-sanic/.venv/lib/python3.12/site-packages/sanic/touchup/schemes/ode.py:70: DeprecationWarning: Attribute s is deprecated and will be removed in Python 3.14; use value instead if hasattr(event, "s"):
[2024-05-13 11:56:27 +0300] [37012] [INFO] Starting worker [37012]
[2024-05-13 11:56:31 +0300] [37083] [INFO] I'm worker
^Cdone
[2024-05-13 11:56:34 +0300] [37003] [INFO] Received signal SIGINT. Shutting down.
[2024-05-13 11:56:34 +0300] [37012] [INFO] Stopping worker [37012]
[2024-05-13 11:56:34 +0300] [37012] [ERROR] Event loop stopped before Future completed.
Traceback (most recent call last):
  File "/home/koka/work/python/saymon/netscan-sanic/.venv/lib/python3.12/site-packages/sanic/worker/serve.py", line 117, in worker_serve
    return _serve_http_1(
           ^^^^^^^^^^^^^^
  File "/home/koka/work/python/saymon/netscan-sanic/.venv/lib/python3.12/site-packages/sanic/server/runners.py", line 301, in _serve_http_1
    _run_server_forever(
  File "/home/koka/work/python/saymon/netscan-sanic/.venv/lib/python3.12/site-packages/sanic/server/runners.py", line 187, in _run_server_forever
    cleanup()
  File "/home/koka/work/python/saymon/netscan-sanic/.venv/lib/python3.12/site-packages/sanic/server/runners.py", line 283, in _cleanup
    loop.run_until_complete(asyncio.sleep(0.1))
  File "uvloop/loop.pyx", line 1515, in uvloop.loop.Loop.run_until_complete
RuntimeError: Event loop stopped before Future completed.
[2024-05-13 11:56:34 +0300] [37003] [INFO] Server Stopped

```

is this a mistake or am I doing something wrong?

### Code snippet

```
from time import sleep
from sanic import Sanic, Request
from sanic.log import logger
from sanic.response import text

app = Sanic(__name__)


def worker() -> None:
    try:
        while True:
            logger.info(f"I'm worker")
            sleep(30)
    except KeyboardInterrupt:
        print("done")


@app.main_process_ready
async def ready(app: Sanic):
    app.manager.manage("SomeWorker", worker, {}, transient=True, restartable=True)


@app.get("/restart")
async def restart_handler(request: Request):
    request.app.m.restart("Sanic-SomeWorker-0")
    return text(request.app.m.name)


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000, motd=False)

```

### How do you run Sanic?

As a script (`app.run` or `Sanic.serve`)

### Operating System

Linux

### Sanic Version

23.12.1

**Comment by ahopkins** [comment]
I do not think there is anything wrong,but I also cannot replicated this behavior.

**Comment by prryplatypus** [comment]
Someone (`invk7244`) posted the following example in our Discord to replicate this:
```py
import asyncio

from sanic import Sanic
from sanic.response import text


Sanic.START_METHOD_SET = True
Sanic.start_method = "fork"


async def index(request):
    return text("dummy")


async def wait_some_time(app, loop):
	"""Operations to perform on server shutdown. 
	For demo just a sleep"""
    await asyncio.sleep(5)


def make_app() -> Sanic:
    app = Sanic(name="dummy")
    app.add_route(index, "/")
    app.register_listener(wait_some_time, "before_server_stop")

    return app


def run_server():
    app = make_app()
    app.run(host="0.0.0.0", port=8000, single_process=True)


if __name__ == "__main__":
    run_server()
```

**Comment by NikPaushkin** [comment]
Yes. Facing the same, can't gracefully shut down my tasks due to this issue.

**Comment by prinf** [comment]
Having the same issue...

**Comment by jsoques** [comment]
I'm having the same issue with a simple hello world get route. If no request is issued to the server then a Ctrl+C shuts down gracefully but as soon as a request is issued, a Ctrl+C errors with the message:  _ERROR:    Event loop stopped before Future completed._

```
from sanic import Request, Sanic
from sanic.response import text

app = Sanic("SecureSanic")


@app.get("/")
async def hello_world(request: Request):
    return text("Hello, world.")

```

**Comment by jsoques** [comment]
Just an FYI, if I run the app with uvicorn, it shuts down gracefully without any issues.

**Comment by dhensen** [comment]
and another one, isolated example (v25.3.0, happens with 24.12.0 as well):

![Image](https://github.com/user-attachments/assets/db2d3119-546b-4286-a262-ea4722e5f20a)

But happens in a semi-serious application since roughly 2024-08-09 looking at my logs.
This happened around that time:
-sanic = "^23.6.0"
+sanic = "^24.6.0"

**Comment by dhensen** [comment]
works using 23.6.0:

![Image](https://github.com/user-attachments/assets/3b44436e-669c-4bea-8e56-6f1d25578f44)

```python
import asyncio

from sanic import Sanic
from sanic.log import logger

app = Sanic("graceful_shutdown_example")
# app.config.GRACEFUL_SHUTDOWN_TIMEOUT = 30 # default 15 is enough


async def cleanup_tasks():
    logger.info("cleaning up tasks")
    await asyncio.sleep(5)
    # await app.ctx.redis.publish("verify:1", app.ctx.stop_word)
    logger.info("tasks cleaned up")


@app.before_server_stop
async def stop_redis_tasks(app):
    logger.info("closing redis")

    await cleanup_tasks()

    logger.info("this will never be printed")


@app.get("/")
async def test(request):
    return "Hello World"


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=1337, auto_reload=True)
```

**Comment by dhensen** [comment]
Looks like this started happening since 23.12.

**Comment by Tronic** [comment]
I am frequently seeing this on Sanic 25.3.

In my case, it hangs after server "goodbye", needing another Ctrl-C to actually terminate. Possibly due to my worker threads not being correctly joined (I do that in @app.after_server_stop).

```
^CMai 07:25:42 INFO:   Received signal SIGINT. Shutting down.
Main  07:25:42 DEBUG:  Terminating a process: Sanic-Server-0-0 [53469]
Srv 0 07:25:42 INFO:   Stopping worker [53469]
Main  07:25:42 DEBUG:  Terminating a process: Sanic-Reloader-0 [53470]
Executing <Task pending name='Task-10' coro=<Sanic._server_event() running at /home/user/cista-storage/.venv/lib/python3.12/site-packages/sanic/app.py:2443> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.12/asyncio/futures.py:387, Task.task_wakeup()] created at /usr/lib/python3.12/asyncio/futures.py:417> cb=[run_until_complete.<locals>.done_cb()] created at /usr/lib/python3.12/asyncio/tasks.py:695> took 0.595 seconds
Srv 0 07:25:42 ERROR:  Event loop stopped before Future completed.
Traceback (most recent call last):
  File "/home/user/cista-storage/.venv/lib/python3.12/site-packages/sanic/worker/serve.py", line 121, in worker_serve
    return _serve_http_1(
           ^^^^^^^^^^^^^^
  File "/home/user/cista-storage/.venv/lib/python3.12/site-packages/sanic/server/runners.py", line 304, in _serve_http_1
    _run_server_forever(
  File "/home/user/cista-storage/.venv/lib/python3.12/site-packages/sanic/server/runners.py", line 192, in _run_server_forever
    loop.run_until_complete(after_stop())
  File "uvloop/loop.pyx", line 1516, in uvloop.loop.Loop.run_until_complete
RuntimeError: Event loop stopped before Future completed.
Main  07:25:52 INFO:   Server Stopped
Main  07:25:52 DEBUG:  Bye
^CMai 07:26:02 INFO:   Shutdown interrupted. Killing.
Main  07:26:02 INFO:   Killing Sanic-Server-0-0 [53469]
```

I am also seeing another type of hang on exit, also needing Ctrl-C twice, no traceback is displayed despite the header saying so:

```
^CProcess Sanic-Server-0-0:
Main  07:24:15 INFO:   Received signal SIGINT. Shutting down.
Main  07:24:15 DEBUG:  Terminating a process: Sanic-Server-0-0 [52587]
Main  07:24:15 DEBUG:  Terminating a process: Sanic-Reloader-0 [52588]
^CTraceback (most recent call last):
Main  07:24:28 INFO:   Shutdown interrupted. Killing.
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
Main  07:24:28 INFO:   Killing Sanic-Server-0-0 [52587]
```

This looks to me a lot like a thread still running after the main thread exits.

**Comment by Tronic** [comment]
When this occurred, the `@app.after_server_stop` signal was not firing, so the threads were definitely left running causing the hang. But this doesn't say what caused the asyncio error.

After moving my cleanup instead to `@app.before_server_stop` I no longer see any exceptions, and it only rarely hangs:

```
^CMai 07:52:38 INFO:   Received signal SIGINT. Shutting down.
Main  07:52:38 DEBUG:  Terminating a process: Sanic-Server-0-0 [67798]
Srv 0 07:52:38 INFO:   Stopping worker [67798]
Srv 0 07:52:38 DEBUG:  Stopping watcher thread
Main  07:52:38 DEBUG:  Terminating a process: Sanic-Reloader-0 [67799]
Srv 0 07:52:39 DEBUG:  Shutting down thread executor
Srv 0 07:52:39 DEBUG:  All shut down
Executing <Task finished name='Task-12' coro=<Sanic._server_event() done, defined at /home/user/cista-storage/.venv/lib/python3.12/site-packages/sanic/app.py:2425> result=None created at /usr/lib/python3.12/asyncio/tasks.py:695> took 0.789 seconds
Srv 0 07:52:39 ACCESS: 127.0.0.1:55015  🔌 ws://localhost:8000/api/watch      1000 NORMAL from server 
Srv 0 07:52:39 INFO:   Worker complete [67798]
^CMai 07:53:03 INFO:   Shutdown interrupted. Killing.
Main  07:53:03 INFO:   Killing Sanic-Server-0-0 [67798]
```

Note: my threads were all already shutdown correctly (shown by three of the debug messages), prior to Worker complete where it hung for no clear reason.
