### ISSUE TITLE
Dependency injection not working for websocket handlers

### ISSUE THREAD

**Issue by dhensen** [sanic-org/sanic#2993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

dependency injection is not working for websocket handlers:
![image](https://github.com/user-attachments/assets/323d93d8-68d9-43e1-a097-0aa03b6f33c8)

```
Traceback (most recent call last):
  File "handle_request", line 102, in handle_request
    if TYPE_CHECKING:
                      
  File "/home/dino/work/gpt-website/.venv/lib/python3.11/site-packages/sanic/app.py", line 1464, in _websocket_handler
    fut = ensure_future(handler(request, ws, *args, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: feed() missing 1 required positional argument: 'db_session'
```

### Code snippet

```python
@websocket_bp.websocket("/ws")
async def your_ws_handler(request: Request, ws: Websocket, db_session: AsyncSession):
    pass
```

### Expected Behavior

Dependency injection injects db_session positional argument without raising exception.

### How do you run Sanic?

As a script (`app.run` or `Sanic.serve`)

### Operating System

Linux

### Sanic Version

24.6.0

**Comment by dhensen** [comment]
Oops, I forgot to uncomment this: 
![image](https://github.com/user-attachments/assets/fd749596-0d43-48d3-a28e-fa4f597bfc9d)

In my testsuite I have a different add_dependency for AsyncSession, I wanted to rule something out but forgot to uncomment it again. My bad!
