### ISSUE TITLE
Multiprocessing-fork does not properly kill instances on stop/restart

### ISSUE THREAD

**Issue by cnicodeme** [sanic-org/sanic#2997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When restarting Sanic, some (forked) process might not be killed properly, causing them to stay alive and increasing the resouce usage (memory, cpu).

In the long run, after multiple restarts, this leads to a system becoming instable.

Here's a copy of the `ps aux | grep [m]ultiproc` command:

```
user     3317222  0.0  0.7 1397988 513156 ?      Sl   Aug21   4:33 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=18) --multiprocessing-fork
user     3317224  0.0  0.6 1227500 436072 ?      Sl   Aug21   3:22 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=20) --multiprocessing-fork
user     3317226  0.0  0.4 1257428 325252 ?      Sl   Aug21   2:18 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=22) --multiprocessing-fork
user     3317228  0.0  1.3 1496080 902568 ?      Sl   Aug21  12:32 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=24) --multiprocessing-fork
user     3317230  0.0  0.9 1256720 609312 ?      Sl   Aug21   7:53 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=26) --multiprocessing-fork
user     3317232  0.0  1.1 1390208 732892 ?      Sl   Aug21   8:20 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=28) --multiprocessing-fork
user     3317233  0.0  1.0 1441388 686740 ?      Sl   Aug21   6:40 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=30) --multiprocessing-fork
user     3317235 92.8  1.6 1480008 1053132 ?     Rl   Aug21 29348:51 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=32) --multiprocessing-fork
user     3317238  0.0  1.3 1433156 904704 ?      Sl   Aug21  11:20 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=34) --multiprocessing-fork
user     3317239  0.0  1.0 1273864 675260 ?      Sl   Aug21   9:42 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=36) --multiprocessing-fork
user     3317241  0.0  0.8 1338840 548328 ?      Sl   Aug21   5:52 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=39) --multiprocessing-fork
user     3317242  0.0  1.3 1368812 880972 ?      Sl   Aug21  14:40 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=64) --multiprocessing-fork
user     3868075  0.0  0.0  15044 11120 ?        S    Mar19   0:00 /var/www/project/env/bin/python -c from multiprocessing.resource_tracker import main;main(5)
user     3868076  2.4  0.0 1093636 41204 ?       Sl   Mar19 6260:56 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=8) --multiprocessing-fork
user     3868085  0.0  0.0  15044 10980 ?        S    Mar19   0:00 /var/www/project/env/bin/python -c from multiprocessing.resource_tracker import main;main(5)
user     3868086  2.5  0.0 1250296 61720 ?       Sl   Mar19 6382:19 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=8) --multiprocessing-fork
user     3868094  0.0  0.0  62500 37468 ?        S    Mar19   0:02 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=18) --multiprocessing-fork
user     3868095  0.0  0.0  62496 37180 ?        S    Mar19   0:28 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=20) --multiprocessing-fork
user     3868096  0.0  0.0  62496 37304 ?        S    Mar19   0:04 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=22) --multiprocessing-fork
user     3868097  0.0  0.0  62500 37212 ?        S    Mar19   0:01 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=24) --multiprocessing-fork
user     3868098  0.0  0.0  62496 37468 ?        S    Mar19   0:08 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=26) --multiprocessing-fork
user     3868099  0.0  0.0  62496 37520 ?        S    Mar19   0:06 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=28) --multiprocessing-fork
user     3868100  0.0  0.0  62504 37476 ?        S    Mar19   0:13 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=30) --multiprocessing-fork
user     3868101  0.0  0.0  62504 37468 ?        S    Mar19   0:18 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=32) --multiprocessing-fork
user     3868102  0.0  0.0  62492 37188 ?        S    Mar19   0:48 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=34) --multiprocessing-fork
user     3868103  0.0  0.0  62500 37456 ?        S    Mar19   1:05 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=36) --multiprocessing-fork
user     3868104  0.0  0.0  62496 37268 ?        S    Mar19   0:36 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=38) --multiprocessing-fork
user     3868105  0.0  0.0  62496 37228 ?        S    Mar19   1:29 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=40) --multiprocessing-fork
user     3868106  0.6  0.0  61112 34804 ?        S    Mar19 1555:37 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=42) --multiprocessing-fork
user     3868152  1.1  0.0  86668 56932 ?        S    Mar19 2815:44 /var/www/project/env/bin/python -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=42) --multiprocessing-fork
```

### Code snippet

Sanic is started using Supervisor with the following script:

```
[program:myapp]
user = user
command=/var/www/myapp/env/bin/python /var/www/myapp/www/server.py --prod
autostart=true
autorestart=true
stopsignal=INT
startsecs=2
stopwaitsecs=5
```

And here's the content of `server.py` used by Supervisor (nothing fancy):

```python
#!./env/bin/python
# -*- coding:utf-8 -*-

from app import App
import sys, os, argparse

sys.path.append(os.path.dirname(os.path.realpath(__file__)))

app = App().app

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Start the Sanic[Fernand] server')
    args = parser.parse_args()

    autoreload = None

    app.run(**{
        'host': '127.0.0.1',
        'port': 5000,
        'dev': False,
        'access_log': False,
        'fast': True
    })
```

### Expected Behavior

When stopping Sanic, all processes should be stopped, including the forked one.

### How do you run Sanic?

Sanic CLI

### Operating System

Linux

### Sanic Version

23.12

### Additional context

I'm not sure about the Sanic version because process were as old as March and at the time, we were using Sanic==23.12

**Comment by ahopkins** [comment]
This is not something that I can reproduce. I am closing the ticket for now, but if there is more context or some other way I can see this happening, please LMK.

**Comment by kuchara** [comment]
I've also hit similar issue. I am able to reproduce this by the following:
```
from sanic import Sanic
from sanic.log import logger
import time

app = Sanic("HelloWorld")

@app.listener('before_server_start')
async def init(app, loop):
    logger.info("Server starting...")
    logger.info("Going to sleep for %s seconds...", app.config.CUSTOM_DELAY)
    time.sleep(app.config.CUSTOM_DELAY)
    logger.info(f"finished initialization.")

@app.route("/")
async def hello_world(request):
    pass

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000, workers=1)
```

When all workers initialize, issue is not reproducible (I am unable to):
```SANIC_CUSTOM_DELAY=1 python3 server.py```

To reproduce, use high value for SANIC_CUSTOM_DELAY, and hit Ctrl+C (or `kill -TERM main_process_pid`):
```SANIC_CUSTOM_DELAY=100 python3 server.py```

On the other shell, one may notice 4 processes:
```
0 R kuchara  1194   527 36  80   0 - 11255 -      15:31 pts/3    00:00:01 python3 server.py
0 S kuchara  1196  1194  0  80   0 -  4825 pipe_r 15:31 pts/3    00:00:00 /home/kuchara/venv/bin/python3 -c from multiprocessing.resource_tracker import main;main(5)
0 S kuchara  1197  1194 28  80   0 - 48018 futex_ 15:31 pts/3    00:00:01 /home/kuchara/venv/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_ha
0 Z kuchara  1204  1194  6  80   0 -     0 -      15:31 pts/3    00:00:00 [python3] <defunct>
```

After I hit Ctrl+C for the second time, this is unblocked.

**Comment by kuchara** [comment]
@ahopkins, can you confirm this, and reopen issue?

**Comment by kuchara** [comment]
I did some more tests on this issue and there are a few problems with handling signals during startup procedure.

1. When signal arrives during worker initialization, there is some sort of a deadloop in wait_for_ack()  (possible fix in PR #3063).
2. When signal arrives somewhere between sync_manager = Manager() is initialized and before signal handlers are set up, Manager process and its resource tracker is not cleaned up. Note that default signal is to terminate process, meaning main process finishes, but leaves orphaned Manager, et al. 
4. Sometimes I've seen that after receiving signal, a few workers terminate, however startup procedure continued, and some other workers started.
5. However I was able to interrupt starting procedure during sync_manager = Manager(). 

To reproduce, I am using:

    SANIC_CUSTOM_DELAY=0 python3 ./server.py  & pid=$! ; sleep 0.6 ; kill $pid

And fine-tune delay in the sleep command.

One of the eamples with a few workers left:

> [2025-05-16 15:48:40 +0200] [60658] [DEBUG] Creating multiprocessing context using 'spawn'
[2025-05-16 15:48:40 +0200] [60658] [DEBUG] Starting a process: Sanic-Server-0-0
[2025-05-16 15:48:40 +0200] [60658] [DEBUG] Starting a process: Sanic-Server-1-0
[2025-05-16 15:48:40 +0200] [60658] [DEBUG] Starting a process: Sanic-Server-2-0
[2]   Terminated              SANIC_CUSTOM_DELAY=0 python3 ./server.py
[2025-05-16 15:48:40 +0200] [60658] [INFO] Received signal SIGTERM. Shutting down.
[2025-05-16 15:48:40 +0200] [60658] [DEBUG] Terminating a process: Sanic-Server-0-0 [60669]
(venv) [kuchara@host sanic]$ Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: [2025-05-16 15:48:40 +0200] [60658] [DEBUG] Terminating a process: Sanic-Server-1-0 [60670]
initialized
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1176, in exec_module
  File "<frozen site>", line 643, in <module>
  File "<frozen site>", line 626, in main
  File "<frozen site>", line 558, in venv
  File "<frozen site>", line 413, in addsitepackages
  File "<frozen site>", line 242, in addsitedir
  File "<frozen site>", line 194, in addpackage
  File "<frozen codecs>", line 319, in decode
KeyboardInterrupt
[2025-05-16 15:48:40 +0200] [60658] [DEBUG] Terminating a process: Sanic-Server-2-0 [60671]
[2025-05-16 15:48:40 +0200] [60658] [DEBUG] Starting a process: Sanic-Server-3-0
[2025-05-16 15:48:40 +0200] [60658] [DEBUG] Starting a process: Sanic-Server-4-0
[2025-05-16 15:48:40 +0200] [60673] [INFO] Server starting...
[2025-05-16 15:48:40 +0200] [60672] [INFO] Server starting...
[2025-05-16 15:48:40 +0200] [60672] [INFO] workers={'Sanic-Main': {'pid': 60658}, 'Sanic-Server-0-0': {'server': True, 'state': 'TERMINATED', 'pid': 60669, 'start_at': datetime.datetime(2025, 5, 16, 13, 48, 40, 488554, tzinfo=datetime.timezone.utc), 'starts': 1}, 'Sanic-Server-1-0': {'server': True, 'state': 'TERMINATED', 'pid': 60670, 'start_at': datetime.datetime(2025, 5, 16, 13, 48, 40, 494740, tzinfo=datetime.timezone.utc), 'starts': 1}, 'Sanic-Server-2-0': {'server': True, 'state': 'TERMINATED', 'pid': 60671, 'start_at': datetime.datetime(2025, 5, 16, 13, 48, 40, 506112, tzinfo=datetime.timezone.utc), 'starts': 1}, 'Sanic-Server-3-0': {'server': True, 'state': 'JOINED', 'pid': 60672, 'start_at': datetime.datetime(2025, 5, 16, 13, 48, 40, 511260, tzinfo=datetime.timezone.utc), 'starts': 1}, 'Sanic-Server-4-0': {'server': True, 'state': 'STARTED', 'pid': 60673, 'start_at': datetime.datetime(2025, 5, 16, 13, 48, 40, 517489, tzinfo=datetime.timezone.utc), 'starts': 1}}
[2025-05-16 15:48:40 +0200] [60672] [INFO] Going to sleep for 0 seconds...
[2025-05-16 15:48:40 +0200] [60672] [INFO] finished initialization.
[2025-05-16 15:48:40 +0200] [60672] [DEBUG] Process ack: Sanic-Server-3-0 [60672]
[2025-05-16 15:48:40 +0200] [60673] [INFO] workers={'Sanic-Main': {'pid': 60658}, 'Sanic-Server-0-0': {'server': True, 'state': 'TERMINATED', 'pid': 60669, 'start_at': datetime.datetime(2025, 5, 16, 13, 48, 40, 488554, tzinfo=datetime.timezone.utc), 'starts': 1}, 'Sanic-Server-1-0': {'server': True, 'state': 'TERMINATED', 'pid': 60670, 'start_at': datetime.datetime(2025, 5, 16, 13, 48, 40, 494740, tzinfo=datetime.timezone.utc), 'starts': 1}, 'Sanic-Server-2-0': {'server': True, 'state': 'TERMINATED', 'pid': 60671, 'start_at': datetime.datetime(2025, 5, 16, 13, 48, 40, 506112, tzinfo=datetime.timezone.utc), 'starts': 1}, 'Sanic-Server-3-0': {'server': True, 'state': 'JOINED', 'pid': 60672, 'start_at': datetime.datetime(2025, 5, 16, 13, 48, 40, 511260, tzinfo=datetime.timezone.utc), 'starts': 1}, 'Sanic-Server-4-0': {'server': True, 'state': 'STARTED', 'pid': 60673, 'start_at': datetime.datetime(2025, 5, 16, 13, 48, 40, 517489, tzinfo=datetime.timezone.utc), 'starts': 1}}
[2025-05-16 15:48:40 +0200] [60673] [INFO] Going to sleep for 0 seconds...
[2025-05-16 15:48:40 +0200] [60673] [INFO] finished initialization.
[2025-05-16 15:48:40 +0200] [60673] [DEBUG] Process ack: Sanic-Server-4-0 [60673]
[2025-05-16 15:48:40 +0200] [60673] [INFO] Starting worker [60673]
[2025-05-16 15:48:40 +0200] [60672] [INFO] Starting worker [60672]

**Comment by cnicodeme** [comment]
👀
